const LEVELS = { Easy:4, Medium:8, Hard:16, Pro:32 };
const DEFAULT_IMAGE = 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=85';
let level='Medium', imageUrl=DEFAULT_IMAGE, image=new Image(), imageBlob=null, crop=null, pieces=[], groups=[], moves=0, seconds=0, timer=null, localUrl=null;
let layout=null, active=null, hovered=null, previewing=false, dpr=1, gameStarted=false, gameWon=false, rotationEnabled=false, view={zoom:1,panX:0,panY:0};
let sessionDirty=false;
let currentSessionId=null;
let pendingSessionId=null,puzzleName='';
const SAVE_VERSION=3; // Increment when a schema change cannot be safely read by older app code.
const canvas=document.querySelector('#puzzleCanvas'), ctx=canvas.getContext('2d'), stage=document.querySelector('#stage'), address=document.querySelector('#imageAddress');
address.value=DEFAULT_IMAGE;
const themeMedia=matchMedia('(prefers-color-scheme: dark)');
function applyTheme(preference,save=true){const resolved=preference==='system'?(themeMedia.matches?'dark':'light'):preference;document.documentElement.dataset.theme=resolved;document.querySelector('#themeSelect').value=preference;if(save)try{localStorage.setItem('puzzlr-theme',preference)}catch{}if(layout)draw()}
let themePreference='system';try{themePreference=localStorage.getItem('puzzlr-theme')||'system'}catch{}applyTheme(themePreference,false);document.querySelector('#themeSelect').onchange=event=>{themePreference=event.target.value;applyTheme(themePreference)};const followSystemTheme=()=>{if(themePreference==='system')applyTheme('system',false)};if(themeMedia.addEventListener)themeMedia.addEventListener('change',followSystemTheme);else themeMedia.addListener(followSystemTheme);

function openSessionDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open('puzzlr-sessions',1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('sessions'))request.result.createObjectStore('sessions',{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function sessionRequest(mode,operation){const db=await openSessionDB();return new Promise((resolve,reject)=>{const tx=db.transaction('sessions',mode),request=operation(tx.objectStore('sessions'));request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close()})}
const getSession=id=>sessionRequest('readonly',store=>store.get(id));
const getSessions=()=>sessionRequest('readonly',store=>store.getAll());
const putSession=value=>sessionRequest('readwrite',store=>store.put(value));
const removeSession=id=>sessionRequest('readwrite',store=>store.delete(id));
async function captureRemoteImage(){if(imageBlob||!imageUrl||imageUrl.startsWith('blob:'))return imageBlob;try{const response=await fetch(imageUrl,{mode:'cors',referrerPolicy:'no-referrer'});if(response.ok)imageBlob=await response.blob()}catch{}return imageBlob}
function createSessionId(){if(globalThis.crypto?.randomUUID)return crypto.randomUUID();return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,char=>{const value=Math.random()*16|0,bits=char==='x'?value:value&3|8;return bits.toString(16)})}
const defaultPuzzleName=id=>id.slice(0,8);
async function uniquePuzzleName(desired,excludeId=null){const base=(desired||'Puzzle').trim()||'Puzzle',names=(await getSessions()).filter(save=>save.id!==excludeId).map(save=>(save.name||'').toLocaleLowerCase());if(!names.includes(base.toLocaleLowerCase()))return base;let number=2;while(names.includes(`${base} ${number}`.toLocaleLowerCase()))number++;return`${base} ${number}`}
async function saveSession(silent=false){if(!gameStarted){if(!silent)alert('Start a puzzle before saving a session.');return false}const button=document.querySelector('#saveSession'),oldText=button.textContent;if(!silent)button.textContent='Saving…';try{await captureRemoteImage();const savedAt=Date.now();currentSessionId||=createSessionId();puzzleName=await uniquePuzzleName(puzzleName||defaultPuzzleName(currentSessionId),currentSessionId);const data={id:currentSessionId,version:SAVE_VERSION,name:puzzleName,savedAt,imageUrl:imageUrl.startsWith('blob:')?null:imageUrl,imageBlob,crop,level,rotationEnabled,moves,seconds,gameWon,groups:groups.map(group=>({ids:[...group.ids],dx:group.dx/layout.boardW,dy:group.dy/layout.boardH,rotation:group.rotation||0})),view:{zoom:view.zoom,panX:view.panX/layout.width,panY:view.panY/layout.height}};await putSession(data);sessionDirty=false;if(!silent){button.textContent='Saved ✓';setTimeout(()=>button.textContent=oldText,1400)}await refreshSessionList();return true}catch{if(!silent)button.textContent=oldText;alert('This browser could not save the session. Check that private browsing is off and device storage is available.');return false}}
function loadImagePromise(src){return new Promise((resolve,reject)=>{const next=new Image();next.referrerPolicy='no-referrer';next.onload=()=>resolve(next);next.onerror=reject;next.src=src})}
function compatibleSession(saved){if(!saved||typeof saved.version!=='number'||saved.version>SAVE_VERSION)return null;if(!saved.crop||!Array.isArray(saved.groups)||!saved.view)return null;return saved}
async function resumeSession(id){const saved=compatibleSession(await getSession(id));if(!saved)return alert('This save was created by an unsupported app version or is incomplete. It was left untouched.');clearInterval(timer);try{if(localUrl){URL.revokeObjectURL(localUrl);localUrl=null}imageBlob=saved.imageBlob||null;if(imageBlob){localUrl=URL.createObjectURL(imageBlob);imageUrl=localUrl}else imageUrl=saved.imageUrl||DEFAULT_IMAGE;image=await loadImagePromise(imageUrl);crop=saved.crop;level=Object.hasOwn(LEVELS,saved.level)?saved.level:'Medium';rotationEnabled=!!saved.rotationEnabled;document.querySelector('#allowRotation').checked=rotationEnabled;address.value=saved.imageUrl||'';document.querySelector('#cropWidth').value=Math.round(crop.sw/image.naturalWidth*100);document.querySelector('#cropHeight').value=Math.round(crop.sh/image.naturalHeight*100);const availableX=image.naturalWidth-crop.sw,availableY=image.naturalHeight-crop.sh;document.querySelector('#cropX').value=availableX>0?Math.round(crop.sx/availableX*200-100):0;document.querySelector('#cropY').value=availableY>0?Math.round(crop.sy/availableY*200-100):0;document.querySelector('#boardWidth').value=Math.round(crop.sw);document.querySelector('#boardHeight').value=Math.round(crop.sh);renderLevels();updateCropPreview();makePieces();fitLayout();groups=saved.groups.map(group=>({ids:group.ids.filter(id=>pieces[id]),dx:Number(group.dx||0)*layout.boardW,dy:Number(group.dy||0)*layout.boardH,rotation:Number(group.rotation||0)%4})).filter(group=>group.ids.length);moves=Number(saved.moves||0);seconds=Number(saved.seconds||0);gameWon=!!saved.gameWon;gameStarted=true;sessionDirty=false;currentSessionId=saved.id;puzzleName=saved.name||defaultPuzzleName(saved.id);document.querySelector('#puzzleName').value=puzzleName;view={zoom:Number(saved.view.zoom||1),panX:Number(saved.view.panX||0)*layout.width,panY:Number(saved.view.panY||0)*layout.height};document.querySelector('#boardZoom').value=Math.round(view.zoom*100);document.querySelector('#zoomValue').value=`${Math.round(view.zoom*100)}%`;document.querySelector('#moves').textContent=String(moves).padStart(2,'0');document.querySelector('#time').textContent=formatTime(seconds);updateProgress();document.querySelector('#setupOverlay').hidden=true;document.body.classList.remove('setupOpen');draw();if(!gameWon)timer=setInterval(()=>{seconds++;document.querySelector('#time').textContent=formatTime(seconds)},1000)}catch{alert('The saved session could not be restored. Its image or data may no longer be available.')}}
async function deleteSession(id){if(!confirm('Delete this saved session? This cannot be undone.'))return;await removeSession(id);await refreshSessionList()}
async function renameSession(id){const saved=await getSession(id);if(!saved)return;const entered=prompt('Enter a unique name for this puzzle session:',saved.name||defaultPuzzleName(id));if(entered===null)return;const desired=entered.trim();if(!desired)return alert('The session name cannot be empty.');const unique=await uniquePuzzleName(desired,id);if(unique!==desired)return alert('That name is already used by another saved puzzle.');saved.name=desired;saved.version=Math.max(saved.version||1,SAVE_VERSION);await putSession(saved);if(currentSessionId===id){puzzleName=desired;document.querySelector('#puzzleName').value=desired}await refreshSessionList()}
async function resetSession(id){const saved=compatibleSession(await getSession(id));if(!saved)return alert('This saved puzzle cannot be used as a template.');try{if(localUrl){URL.revokeObjectURL(localUrl);localUrl=null}imageBlob=saved.imageBlob||null;if(imageBlob){localUrl=URL.createObjectURL(imageBlob);imageUrl=localUrl}else imageUrl=saved.imageUrl||DEFAULT_IMAGE;image=await loadImagePromise(imageUrl);crop=saved.crop;level=Object.hasOwn(LEVELS,saved.level)?saved.level:'Medium';rotationEnabled=!!saved.rotationEnabled;document.querySelector('#allowRotation').checked=rotationEnabled;address.value=saved.imageUrl||'';document.querySelector('#cropWidth').value=Math.round(crop.sw/image.naturalWidth*100);document.querySelector('#cropHeight').value=Math.round(crop.sh/image.naturalHeight*100);const availableX=image.naturalWidth-crop.sw,availableY=image.naturalHeight-crop.sh;document.querySelector('#cropX').value=availableX>0?Math.round(crop.sx/availableX*200-100):0;document.querySelector('#cropY').value=availableY>0?Math.round(crop.sy/availableY*200-100):0;document.querySelector('#boardWidth').value=Math.round(crop.sw);document.querySelector('#boardHeight').value=Math.round(crop.sh);pendingSessionId=createSessionId();puzzleName=await uniquePuzzleName(`${saved.name||defaultPuzzleName(saved.id)} reset`);document.querySelector('#puzzleName').value=puzzleName;renderLevels();updateCropPreview();document.querySelector('.newPuzzleDivider').scrollIntoView({behavior:'smooth',block:'start'})}catch{alert('This saved puzzle’s image could not be loaded for reset.')}}
function sessionRow(saved,isLast=false){const row=document.createElement('div');row.className=`sessionRow${isLast?' lastSessionRow':''}`;const status=saved.version>SAVE_VERSION?'Newer app version':`${saved.moves||0} moves · ${new Date(saved.savedAt||0).toLocaleString()}`;const info=document.createElement('div'),title=document.createElement('strong'),detail=document.createElement('small'),actions=document.createElement('div');title.textContent=saved.name||defaultPuzzleName(saved.id);detail.textContent=status;info.append(title,detail);actions.className='sessionActions';actions.innerHTML='<button class="previewSaved">Preview</button><button class="resumeOne">Resume</button><button class="resetSession">Reset</button><button class="renameSession">Rename</button><button class="deleteSession">Delete</button>';row.append(info,actions);bindSavedPreview(actions.querySelector('.previewSaved'),saved);actions.querySelector('.resumeOne').onclick=()=>resumeSession(saved.id);actions.querySelector('.resetSession').onclick=()=>resetSession(saved.id);actions.querySelector('.renameSession').onclick=()=>renameSession(saved.id);actions.querySelector('.deleteSession').onclick=()=>deleteSession(saved.id);return row}
async function refreshSessionList(){try{const saves=(await getSessions()).sort((a,b)=>(b.savedAt||0)-(a.savedAt||0)),root=document.querySelector('#savedSessions'),last=document.querySelector('#lastSession'),list=document.querySelector('#sessionList'),previousTitle=document.querySelector('.previousTitle');root.hidden=!saves.length;last.innerHTML='';list.innerHTML='';if(!saves.length)return;last.append(sessionRow(saves[0],true));previousTitle.hidden=saves.length<2;saves.slice(1).forEach(saved=>list.append(sessionRow(saved)))}catch{document.querySelector('#savedSessions').hidden=true}}

function rand(seed){ const value=Math.sin(seed*999.91)*43758.5453; return value-Math.floor(value); }
function gridForLevel(){const size=LEVELS[level],ratio=crop?crop.sw/crop.sh:(image.naturalWidth/image.naturalHeight||1);return[Math.max(2,Math.round(size*Math.sqrt(ratio))),Math.max(2,Math.round(size/Math.sqrt(ratio)))]}
function edge(seed,sign){ return {sign, width:.36+rand(seed)*.14, depth:.20+rand(seed+3)*.075, lean:(rand(seed+8)-.5)*.12, neck:.48+rand(seed+12)*.16, crown:.82+rand(seed+16)*.14, shoulder:.055+rand(seed+21)*.045}; }
function makePieces(){
  const [cols,rows]=gridForLevel(), vertical=[], horizontal=[];
  for(let r=0;r<rows;r++){vertical[r]=[];for(let c=0;c<cols-1;c++)vertical[r][c]=edge(100+r*cols+c,rand(500+r*cols+c)>.5?1:-1)}
  for(let r=0;r<rows-1;r++){horizontal[r]=[];for(let c=0;c<cols;c++)horizontal[r][c]=edge(900+r*cols+c,rand(1200+r*cols+c)>.5?1:-1)}
  const mate=feature=>({...feature,sign:-feature.sign,lean:-feature.lean});
  pieces=[]; for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)pieces.push({id:r*cols+c,col:c,row:r,edges:{top:r?mate(horizontal[r-1][c]):null,right:c<cols-1?vertical[r][c]:null,bottom:r<rows-1?horizontal[r][c]:null,left:c?mate(vertical[r][c-1]):null}});
}
function fitLayout(){
  const width=stage.clientWidth, [cols,rows]=gridForLevel(), mobile=width<640, imageRatio=crop?crop.sw/crop.sh:(image.naturalWidth/image.naturalHeight||cols/rows);
  let boardW=mobile?Math.min(width-28,560):Math.min(width*.7,920), boardH=boardW/imageRatio;
  const maxBoardH=mobile?Math.min(560,width*1.15):480;if(boardH>maxBoardH){boardH=maxBoardH;boardW=boardH*imageRatio}
  const trayH=mobile?Math.max(boardH*.55,Math.min(260,width*.55)):0,stageRect=stage.getBoundingClientRect(),stageTop=window.scrollY+stageRect.top,workspaceBottom=window.scrollY+document.querySelector('.workspace').getBoundingClientRect().bottom,contentAfterStage=Math.max(0,workspaceBottom-(window.scrollY+stageRect.bottom)),availableHeight=window.innerHeight-stageTop-contentAfterStage,height=Math.max(1,availableHeight);
  const boardX=(width-boardW)/2, boardY=(height-boardH)/2;
  layout={width,height,boardX,boardY,boardW,boardH,cellW:boardW/cols,cellH:boardH/rows,mobile};
  dpr=Math.min(window.devicePixelRatio||1,2); canvas.width=width*dpr;canvas.height=height*dpr;canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;ctx.setTransform(dpr,0,0,dpr,0,0);
}
function scatter(){
  fitLayout();groups=pieces.map(piece=>({ids:[piece.id],dx:0,dy:0,rotation:0}));positionGroups(groups,true);
}
function groupBounds(group){const members=group.ids.map(id=>pieces[id]),minCol=Math.min(...members.map(piece=>piece.col)),maxCol=Math.max(...members.map(piece=>piece.col)),minRow=Math.min(...members.map(piece=>piece.row)),maxRow=Math.max(...members.map(piece=>piece.row));return{minCol,maxCol,minRow,maxRow,width:(maxCol-minCol+1)*layout.cellW,height:(maxRow-minRow+1)*layout.cellH}}
function groupCenter(group){const bounds=groupBounds(group);return{x:layout.boardX+(bounds.minCol+bounds.maxCol+1)*layout.cellW/2+group.dx,y:layout.boardY+(bounds.minRow+bounds.maxRow+1)*layout.cellH/2+group.dy}}
function rotatePoint(point,center,quarters){const angle=quarters*Math.PI/2,cos=Math.cos(angle),sin=Math.sin(angle),x=point.x-center.x,y=point.y-center.y;return{x:center.x+x*cos-y*sin,y:center.y+x*sin+y*cos}}
function groupIsOnBoard(group){const center=groupCenter(group);return group.ids.some(id=>{const piece=pieces[id],base=piecePosition(piece,group),point=rotatePoint({x:base.x+layout.cellW/2,y:base.y+layout.cellH/2},center,group.rotation||0);return point.x>=layout.boardX&&point.x<=layout.boardX+layout.boardW&&point.y>=layout.boardY&&point.y<=layout.boardY+layout.boardH})}
function positionGroups(list,randomizeRotation=false){const seed=Date.now()%100000,cx=layout.width/2,cy=layout.height/2,toWorld=(x,y)=>({x:(x-cx-view.panX)/view.zoom+cx,y:(y-cy-view.panY)/view.zoom+cy}),topLeft=toWorld(0,0),bottomRight=toWorld(layout.width,layout.height),visible={left:topLeft.x,top:topLeft.y,right:bottomRight.x,bottom:bottomRight.y},boardRight=layout.boardX+layout.boardW,boardBottom=layout.boardY+layout.boardH;
  list.forEach((group,index)=>{if(randomizeRotation&&rotationEnabled)group.rotation=Math.floor(rand(seed+index*19)*4);const bounds=groupBounds(group),turned=(group.rotation||0)%2===1,groupW=turned?bounds.height:bounds.width,groupH=turned?bounds.width:bounds.height,maxX=visible.right-groupW,maxY=visible.bottom-groupH;if(maxX<visible.left||maxY<visible.top)return;let chosen=null;for(let attempt=0;attempt<48;attempt++){const token=seed+index*101+attempt*13,x=visible.left+rand(token)*(maxX-visible.left),y=visible.top+rand(token+7)*(maxY-visible.top),overlapsBoard=x<boardRight&&x+groupW>layout.boardX&&y<boardBottom&&y+groupH>layout.boardY;if(!overlapsBoard){chosen={x,y};break}}if(!chosen)return;const baseCenterX=layout.boardX+(bounds.minCol+bounds.maxCol+1)*layout.cellW/2,baseCenterY=layout.boardY+(bounds.minRow+bounds.maxRow+1)*layout.cellH/2;group.dx=chosen.x+groupW/2-baseCenterX;group.dy=chosen.y+groupH/2-baseCenterY});hovered=null;draw()}
function reshuffleLoose(){positionGroups(groups.filter(group=>!groupIsOnBoard(group)),true);sessionDirty=true}
function addEdge(path,x1,y1,x2,y2,feature,side){
  if(!feature){path.lineTo(x2,y2);return} const horizontal=y1===y2, len=horizontal?x2-x1:y2-y1, dir=Math.sign(len), abs=Math.abs(len), unit=Math.min(layout.cellW,layout.cellH), mid=.5+feature.lean*(unit/abs), half=(feature.width*unit/2)/abs, depth=feature.depth*unit*feature.sign*side;
  const p=(fraction,off=0)=>horizontal?[x1+dir*abs*fraction,y1+off]:[x1+off,y1+dir*abs*fraction];
  const neck=half*feature.neck, crown=half*feature.crown, shoulder=depth*feature.shoulder;
  const a=p(mid-half), b=p(mid-half*.90,-shoulder), c=p(mid-neck*1.18,-shoulder), d=p(mid-neck,depth*.16);
  const e=p(mid-crown,depth*.42), f=p(mid-crown*.78,depth*.92), g=p(mid,depth);
  const h=p(mid+crown*.78,depth*.92), i=p(mid+crown,depth*.42), j=p(mid+neck,depth*.16);
  const k=p(mid+neck*1.18,-shoulder), l=p(mid+half*.90,-shoulder), m=p(mid+half);
  path.lineTo(...a);path.bezierCurveTo(...b,...c,...d);path.bezierCurveTo(...e,...f,...g);path.bezierCurveTo(...h,...i,...j);path.bezierCurveTo(...k,...l,...m);path.lineTo(x2,y2);
}
function piecePath(piece,x,y){
  const w=layout.cellW,h=layout.cellH,path=new Path2D();path.moveTo(x,y);addEdge(path,x,y,x+w,y,piece.edges.top,-1);addEdge(path,x+w,y,x+w,y+h,piece.edges.right,1);addEdge(path,x+w,y+h,x,y+h,piece.edges.bottom,1);addEdge(path,x,y+h,x,y,piece.edges.left,-1);path.closePath();return path;
}
function groupFor(id){return groups.find(group=>group.ids.includes(id))}
function piecePosition(piece,group){return {x:layout.boardX+piece.col*layout.cellW+group.dx,y:layout.boardY+piece.row*layout.cellH+group.dy}}
function draw(){
  const {width,height,boardX,boardY,boardW,boardH,mobile}=layout,themeStyles=getComputedStyle(document.documentElement),stageColor=themeStyles.getPropertyValue('--stage').trim(),boardLine=themeStyles.getPropertyValue('--board-line').trim(),labelColor=themeStyles.getPropertyValue('--label').trim();ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);ctx.save();ctx.translate(width/2+view.panX,height/2+view.panY);ctx.scale(view.zoom,view.zoom);ctx.translate(-width/2,-height/2);
  ctx.fillStyle=stageColor;ctx.fillRect(0,0,width,height);ctx.save();ctx.setLineDash([5,6]);ctx.strokeStyle=boardLine;ctx.lineWidth=1.5;ctx.strokeRect(boardX,boardY,boardW,boardH);ctx.restore();
  ctx.fillStyle=labelColor;ctx.font='700 9px Arial';ctx.letterSpacing='1px';ctx.fillText('ASSEMBLE HERE',boardX+8,boardY+16);
  if(mobile){ctx.fillStyle=labelColor;ctx.fillText('LOOSE PIECES',12,boardY+boardH+25)}
  if(previewing){ctx.save();ctx.globalAlpha=.92;const source=crop||{sx:0,sy:0,sw:image.naturalWidth,sh:image.naturalHeight};ctx.drawImage(image,source.sx,source.sy,source.sw,source.sh,boardX,boardY,boardW,boardH);ctx.restore();ctx.restore();return}
  groups.forEach(group=>{const center=groupCenter(group);ctx.save();ctx.translate(center.x,center.y);ctx.rotate((group.rotation||0)*Math.PI/2);ctx.translate(-center.x,-center.y);group.ids.forEach(id=>{const piece=pieces[id],pos=piecePosition(piece,group),path=piecePath(piece,pos.x,pos.y);ctx.save();ctx.clip(path);const source=crop||{sx:0,sy:0,sw:image.naturalWidth,sh:image.naturalHeight};ctx.drawImage(image,source.sx,source.sy,source.sw,source.sh,pos.x-(piece.col*layout.cellW),pos.y-(piece.row*layout.cellH),layout.boardW,layout.boardH);ctx.restore();const highlighted=group===active?.group||group===hovered;ctx.strokeStyle=highlighted?'#ee5b32':'rgba(35,40,37,.65)';ctx.lineWidth=highlighted?2.5:1;if(highlighted){ctx.save();ctx.shadowColor='rgba(238,91,50,.48)';ctx.shadowBlur=7;ctx.stroke(path);ctx.restore()}else ctx.stroke(path)});ctx.restore()});
  ctx.restore();if(gameWon){const dark=document.documentElement.dataset.theme==='dark';ctx.save();ctx.fillStyle=dark?'rgba(14,18,16,.68)':'rgba(250,248,241,.68)';ctx.fillRect(0,0,width,height);ctx.textAlign='center';ctx.textBaseline='middle';const titleSize=Math.max(38,Math.min(78,width*.075));ctx.font=`italic ${titleSize}px Georgia`;ctx.lineJoin='round';ctx.lineWidth=Math.max(5,titleSize*.1);ctx.strokeStyle=dark?'rgba(0,0,0,.92)':'rgba(255,255,255,.96)';ctx.strokeText('Beautifully done.',width/2,height/2-18);ctx.fillStyle=dark?'#edf2ed':'#18201d';ctx.fillText('Beautifully done.',width/2,height/2-18);ctx.font='700 14px Arial';ctx.lineWidth=4;const result=`${moves} moves · ${formatTime(seconds)}`;ctx.strokeText(result,width/2,height/2+42);ctx.fillStyle=dark?'#ff7650':'#ee5b32';ctx.fillText(result,width/2,height/2+42);ctx.restore()}
}
function screenPointer(event){const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*layout.width/rect.width,y:(event.clientY-rect.top)*layout.height/rect.height}}
function pointer(event){const point=screenPointer(event),cx=layout.width/2,cy=layout.height/2;return{x:(point.x-cx-view.panX)/view.zoom+cx,y:(point.y-cy-view.panY)/view.zoom+cy}}
function hitTest(point){const pad=Math.min(layout.cellW,layout.cellH)*.3;for(let g=groups.length-1;g>=0;g--){const group=groups[g],center=groupCenter(group),testPoint=rotatePoint(point,center,-(group.rotation||0));for(let p=group.ids.length-1;p>=0;p--){const piece=pieces[group.ids[p]],pos=piecePosition(piece,group);if(testPoint.x<pos.x-pad||testPoint.x>pos.x+layout.cellW+pad||testPoint.y<pos.y-pad||testPoint.y>pos.y+layout.cellH+pad)continue;if(ctx.isPointInPath(piecePath(piece,pos.x,pos.y),testPoint.x,testPoint.y))return group}}return null}
function adjacent(a,b){const pa=pieces[a],pb=pieces[b];return Math.abs(pa.col-pb.col)+Math.abs(pa.row-pb.row)===1}
function tryLocks(moving){
  let merged=true;
  if((moving.rotation||0)!==0)return false;while(merged){merged=false;for(const other of [...groups]){if(other===moving||(other.rotation||0)!==0)continue;const neighbors=moving.ids.some(a=>other.ids.some(b=>adjacent(a,b)));const distance=Math.hypot(moving.dx-other.dx,moving.dy-other.dy);if(neighbors&&distance<Math.min(layout.cellW,layout.cellH)*.3){moving.dx=other.dx;moving.dy=other.dy;moving.ids.push(...other.ids);groups.splice(groups.indexOf(other),1);merged=true;break}}}
  return moving.ids.length===pieces.length;
}
canvas.addEventListener('pointerdown',event=>{if(previewing)return;const point=pointer(event),screen=screenPointer(event),group=hitTest(point);if(group){groups.splice(groups.indexOf(group),1);groups.push(group);active={group,last:point,start:screen,moved:false}}else active={panning:true,last:screen,start:screen,moved:false};canvas.setPointerCapture(event.pointerId);draw()});
canvas.addEventListener('pointermove',event=>{if(!active){const next=hitTest(pointer(event));if(next!==hovered){hovered=next;canvas.style.cursor=hovered?'grab':'move';draw()}return}const screen=screenPointer(event);if(Math.hypot(screen.x-active.start.x,screen.y-active.start.y)>5)active.moved=true;if(active.panning){view.panX+=screen.x-active.last.x;view.panY+=screen.y-active.last.y;active.last=screen}else{const point=pointer(event);active.group.dx+=point.x-active.last.x;active.group.dy+=point.y-active.last.y;active.last=point}draw()});
canvas.addEventListener('pointerup',event=>{if(!active)return;if(!active.panning){let won=false;if(!active.moved&&rotationEnabled){active.group.rotation=((active.group.rotation||0)+1)%4;won=tryLocks(active.group)}else if(active.moved)won=tryLocks(active.group);if(active.moved||rotationEnabled){moves++;sessionDirty=true;document.querySelector('#moves').textContent=String(moves).padStart(2,'0')}active=null;updateProgress();draw();if(won)showWin()}else{active=null;draw()}try{canvas.releasePointerCapture(event.pointerId)}catch{}});
canvas.addEventListener('pointerleave',()=>{if(!active&&hovered){hovered=null;draw()}});
function updateProgress(){const largest=Math.max(...groups.map(g=>g.ids.length)),percent=Math.round(largest/pieces.length*100);document.querySelector('#percent').textContent=`${percent}%`;document.querySelector('#progress').style.width=`${percent}%`}
function showWin(){clearInterval(timer);gameWon=true;sessionDirty=true;draw()}
function formatTime(value){return `${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`}
function restart(){clearInterval(timer);moves=0;seconds=0;gameStarted=true;gameWon=false;sessionDirty=false;view={zoom:1,panX:0,panY:0};document.querySelector('#boardZoom').value=100;document.querySelector('#zoomValue').value='100%';document.querySelector('#moves').textContent='00';document.querySelector('#time').textContent='00:00';makePieces();scatter();updateProgress();draw();timer=setInterval(()=>{seconds++;document.querySelector('#time').textContent=formatTime(seconds)},1000)}
function resetCropControls(){document.querySelector('#boardWidth').value=image.naturalWidth;document.querySelector('#boardHeight').value=image.naturalHeight;document.querySelector('#cropWidth').value=100;document.querySelector('#cropHeight').value=100;document.querySelector('#cropX').value=0;document.querySelector('#cropY').value=0;crop=cropValues();document.querySelector('#cropEditor').hidden=false;updateCropPreview();renderLevels()}
function cropValues(){const widthPercent=Number(document.querySelector('#cropWidth').value)/100,heightPercent=Number(document.querySelector('#cropHeight').value)/100,sw=image.naturalWidth*widthPercent,sh=image.naturalHeight*heightPercent,px=(Number(document.querySelector('#cropX').value)+100)/200,py=(Number(document.querySelector('#cropY').value)+100)/200;return{sx:(image.naturalWidth-sw)*px,sy:(image.naturalHeight-sh)*py,sw,sh,targetW:Math.round(sw),targetH:Math.round(sh)}}
function updateCropPreview(){if(!image.naturalWidth)return;const preview=document.querySelector('#cropCanvas'),box=preview.parentElement.clientWidth||360,w=box,h=Math.min(260,w*.64);preview.width=w*devicePixelRatio;preview.height=h*devicePixelRatio;preview.style.width=`${w}px`;preview.style.height=`${h}px`;const c=preview.getContext('2d');c.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);c.clearRect(0,0,w,h);const scale=Math.min(w/image.naturalWidth,h/image.naturalHeight),dw=image.naturalWidth*scale,dh=image.naturalHeight*scale,ox=(w-dw)/2,oy=(h-dh)/2;c.drawImage(image,ox,oy,dw,dh);c.fillStyle='rgba(16,20,18,.58)';c.fillRect(0,0,w,h);const value=cropValues(),rx=ox+value.sx*scale,ry=oy+value.sy*scale,rw=value.sw*scale,rh=value.sh*scale;c.save();c.beginPath();c.rect(rx,ry,rw,rh);c.clip();c.drawImage(image,ox,oy,dw,dh);c.restore();c.strokeStyle='#ee5b32';c.lineWidth=3;c.strokeRect(rx,ry,rw,rh);c.strokeStyle='rgba(255,255,255,.75)';c.lineWidth=1;c.strokeRect(rx+rw/3,ry,0,rh);c.strokeRect(rx+rw*2/3,ry,0,rh);c.strokeRect(rx,ry+rh/3,rw,0);c.strokeRect(rx,ry+rh*2/3,rw,0);document.querySelector('#widthValue').value=`${document.querySelector('#cropWidth').value}%`;document.querySelector('#heightValue').value=`${document.querySelector('#cropHeight').value}%`;const label=value=>value===0?'CENTER':value<0?`${Math.abs(value)}% LEFT / UP`:`${value}% RIGHT / DOWN`;document.querySelector('#xValue').value=label(Number(document.querySelector('#cropX').value));document.querySelector('#yValue').value=label(Number(document.querySelector('#cropY').value))}
function loadImage(url,blob=null){imageBlob=blob;const next=new Image();next.referrerPolicy='no-referrer';next.onload=()=>{image=next;resetCropControls();if(!pieces.length){makePieces();scatter();draw()}};next.onerror=()=>alert('That image host blocked the request or the address is not a direct image link. Try downloading it and choosing it from your device.');next.src=url}
function renderLevels(){const root=document.querySelector('#levels');root.innerHTML='';Object.keys(LEVELS).forEach(name=>{const previous=level;level=name;const[cols,rows]=gridForLevel();level=previous;const button=document.createElement('button');button.className=name===level?'active':'';button.innerHTML=`<strong>${name}</strong><small>${cols} × ${rows} · ${cols*rows}</small>`;button.onclick=()=>{level=name;renderLevels()};root.append(button)})}
async function openSetup(){if(gameStarted&&!gameWon&&sessionDirty){if(confirm('Save your current session before starting a new puzzle?')){if(!await saveSession(true))return}else if(!confirm('Start a new puzzle without saving this session?'))return}clearInterval(timer);pendingSessionId=createSessionId();puzzleName=await uniquePuzzleName(defaultPuzzleName(pendingSessionId));document.querySelector('#puzzleName').value=puzzleName;await refreshSessionList();document.querySelector('#setupOverlay').hidden=false;document.body.classList.add('setupOpen')}
document.querySelector('#restartTop').onclick=openSetup;document.querySelector('#startPuzzle').onclick=async()=>{crop=cropValues();rotationEnabled=document.querySelector('#allowRotation').checked;currentSessionId=pendingSessionId||createSessionId();puzzleName=await uniquePuzzleName(document.querySelector('#puzzleName').value||defaultPuzzleName(currentSessionId),currentSessionId);document.querySelector('#puzzleName').value=puzzleName;pendingSessionId=null;document.querySelector('#setupOverlay').hidden=true;document.body.classList.remove('setupOpen');restart();await saveSession(true)};document.querySelector('#useImage').onclick=()=>{if(address.value.trim()){imageUrl=address.value.trim();loadImage(imageUrl)}};address.onkeydown=e=>{if(e.key==='Enter')document.querySelector('#useImage').click()};document.querySelector('#upload').onclick=()=>document.querySelector('#fileInput').click();document.querySelector('#fileInput').onchange=e=>{const file=e.target.files[0];if(!file)return;if(localUrl)URL.revokeObjectURL(localUrl);localUrl=URL.createObjectURL(file);imageUrl=localUrl;address.value='';loadImage(imageUrl,file)};
document.querySelector('#resetSite').onclick=event=>{event.preventDefault();location.reload()};
let previewPinned=false,previewToken=0;
function showImagePopup(previewImage,source){const popup=document.querySelector('#previewPopup'),previewCanvas=document.querySelector('#previewPopupCanvas'),maxW=window.innerWidth,maxH=window.innerHeight,ratio=source.sw/source.sh;let w=maxW,h=w/ratio;if(h>maxH){h=maxH;w=h*ratio}const ratioDpr=Math.min(devicePixelRatio||1,2);previewCanvas.width=w*ratioDpr;previewCanvas.height=h*ratioDpr;previewCanvas.style.width=`${w}px`;previewCanvas.style.height=`${h}px`;const previewContext=previewCanvas.getContext('2d');previewContext.setTransform(ratioDpr,0,0,ratioDpr,0,0);previewContext.drawImage(previewImage,source.sx,source.sy,source.sw,source.sh,0,0,w,h);popup.hidden=false}
function showPreviewPopup(){previewToken++;showImagePopup(image,crop||{sx:0,sy:0,sw:image.naturalWidth,sh:image.naturalHeight})}
function hidePreviewPopup(){previewToken++;if(!previewPinned){document.querySelector('#previewPopup').hidden=true;document.querySelector('#savedPreviewPopup').hidden=true}}
function showSavedImagePopup(savedImage,source,button){const popup=document.querySelector('#savedPreviewPopup'),savedCanvas=document.querySelector('#savedPreviewCanvas'),ratio=source.sw/source.sh,maxW=Math.min(260,window.innerWidth*.65),maxH=200;let w=maxW,h=w/ratio;if(h>maxH){h=maxH;w=h*ratio}const ratioDpr=Math.min(devicePixelRatio||1,2);savedCanvas.width=w*ratioDpr;savedCanvas.height=h*ratioDpr;savedCanvas.style.width=`${w}px`;savedCanvas.style.height=`${h}px`;const savedContext=savedCanvas.getContext('2d');savedContext.setTransform(ratioDpr,0,0,ratioDpr,0,0);savedContext.drawImage(savedImage,source.sx,source.sy,source.sw,source.sh,0,0,w,h);popup.hidden=false;const rect=button.getBoundingClientRect(),popupW=w+16,popupH=h+16;let left=Math.min(window.innerWidth-popupW-10,rect.right+10),top=Math.min(window.innerHeight-popupH-10,rect.top);if(left<10)left=Math.max(10,rect.left-popupW-10);popup.style.left=`${left}px`;popup.style.top=`${Math.max(10,top)}px`}
async function showSavedPreview(saved,button){const token=++previewToken;try{let url=saved.imageUrl,tempUrl=null;if(saved.imageBlob){tempUrl=URL.createObjectURL(saved.imageBlob);url=tempUrl}if(!url)return;const savedImage=await loadImagePromise(url);if(tempUrl)URL.revokeObjectURL(tempUrl);if(token!==previewToken)return;const source=saved.crop||{sx:0,sy:0,sw:savedImage.naturalWidth,sh:savedImage.naturalHeight};showSavedImagePopup(savedImage,source,button)}catch{if(token===previewToken)document.querySelector('#savedPreviewPopup').hidden=true}}
function bindSavedPreview(button,saved){button.addEventListener('pointerenter',event=>{if(event.pointerType==='mouse'&&!previewPinned)showSavedPreview(saved,button)});button.addEventListener('pointerleave',hidePreviewPopup);button.addEventListener('click',event=>{event.stopPropagation();previewPinned=!previewPinned;if(previewPinned)showSavedPreview(saved,button);else{previewToken++;document.querySelector('#savedPreviewPopup').hidden=true}})}
const preview=document.querySelector('#preview'),previewPopup=document.querySelector('#previewPopup');preview.addEventListener('pointerenter',event=>{if(event.pointerType==='mouse'&&!previewPinned)showPreviewPopup()});preview.addEventListener('pointerleave',hidePreviewPopup);preview.addEventListener('focus',()=>{if(!previewPinned)showPreviewPopup()});preview.addEventListener('blur',hidePreviewPopup);preview.addEventListener('click',event=>{event.stopPropagation();previewPinned=!previewPinned;if(previewPinned)showPreviewPopup();else{previewToken++;previewPopup.hidden=true}});document.addEventListener('click',event=>{if(previewPinned&&!event.target.closest('#preview,.previewSaved')){previewPinned=false;previewToken++;previewPopup.hidden=true;document.querySelector('#savedPreviewPopup').hidden=true}});
function syncCrop(){crop=cropValues();document.querySelector('#boardWidth').value=Math.round(crop.sw);document.querySelector('#boardHeight').value=Math.round(crop.sh);updateCropPreview();renderLevels()}
['cropWidth','cropHeight','cropX','cropY'].forEach(id=>document.querySelector(`#${id}`).addEventListener('input',syncCrop));
['boardWidth','boardHeight'].forEach(id=>document.querySelector(`#${id}`).addEventListener('input',()=>{document.querySelector('#cropWidth').value=Math.max(10,Math.min(100,Number(document.querySelector('#boardWidth').value)/image.naturalWidth*100));document.querySelector('#cropHeight').value=Math.max(10,Math.min(100,Number(document.querySelector('#boardHeight').value)/image.naturalHeight*100));syncCrop()}));
document.querySelector('#resetCrop').onclick=resetCropControls;
function setZoom(value,anchor=null){const next=Math.max(.5,Math.min(1.8,value));if(anchor){const cx=layout.width/2,cy=layout.height/2,worldX=(anchor.x-cx-view.panX)/view.zoom+cx,worldY=(anchor.y-cy-view.panY)/view.zoom+cy;view.panX=anchor.x-cx-next*(worldX-cx);view.panY=anchor.y-cy-next*(worldY-cy)}view.zoom=next;document.querySelector('#boardZoom').value=Math.round(view.zoom*100);document.querySelector('#zoomValue').value=`${Math.round(view.zoom*100)}%`;draw()}
document.querySelector('#boardZoom').oninput=e=>setZoom(Number(e.target.value)/100);document.querySelector('#zoomOut').onclick=()=>setZoom(view.zoom-.1);document.querySelector('#zoomIn').onclick=()=>setZoom(view.zoom+.1);document.querySelector('#centerView').onclick=()=>{view.panX=0;view.panY=0;draw()};
document.querySelector('#reshuffleLoose').onclick=reshuffleLoose;
document.querySelector('#saveSession').onclick=()=>saveSession(false);
canvas.addEventListener('wheel',event=>{event.preventDefault();const anchor=screenPointer(event),factor=Math.exp(-event.deltaY*.0015);setZoom(view.zoom*factor,anchor)},{passive:false});
window.addEventListener('resize',()=>{if(!pieces.length)return;const old=layout;fitLayout();groups.forEach(group=>{group.dx*=layout.boardW/old.boardW;group.dy*=layout.boardH/old.boardH});view.panX*=layout.width/old.width;view.panY*=layout.height/old.height;draw()});window.addEventListener('beforeunload',event=>{if(gameStarted&&!gameWon&&sessionDirty){event.preventDefault();event.returnValue=''}if(localUrl)URL.revokeObjectURL(localUrl)});
pendingSessionId=createSessionId();puzzleName=defaultPuzzleName(pendingSessionId);document.querySelector('#puzzleName').value=puzzleName;renderLevels();document.body.classList.add('setupOpen');loadImage(DEFAULT_IMAGE);refreshSessionList();
