const LEVELS = { Easy:4, Medium:8, Hard:16, Pro:32 };
const DEFAULT_IMAGE = 'public/default-fantasy-festival.png';
let level='Medium', imageUrl=DEFAULT_IMAGE, image=new Image(), imageBlob=null, crop=null, pieces=[], groups=[], moves=0, seconds=0, timer=null, localUrl=null;
let layout=null, active=null, hovered=null, previewing=false, dpr=1, gameStarted=false, gameWon=false, winStartedAt=0,winAnimationFrame=null,rippleStartedAt=0,rippleOrigin=null,completionShadowsDisabled=false,rotationEnabled=false, view={zoom:1,panX:0,panY:0};
let sessionDirty=false;
let currentSessionId=null;
let pendingSessionId=null,puzzleName='';
let cropInteraction=null,cropMetrics=null;
let glowEnabled=true,bevelEnabled=true,pieceOutlinesEnabled=false,cacheDebugEnabled=false,bevelAtlases=null,bevelGeneration=0;
let staticFrame=null,cacheGeneration=0,cacheRefineTimer=null,cacheRefineToken=0,cacheRefineWorkHandle=null,cacheRefineWorkKind=null,cacheRefineBuilder=null,navigationFrame=null,navigationBase=null,navigationTimer=null,navigationExcluded=null,navigationDrawFrame=null,edgePanFrame=null,edgePanLastTime=0,pinchGesture=null;
const renderMetrics={captureMs:0,navigationDrawMs:0,cacheBuildMs:0,cacheQueue:0};
const SAVE_VERSION=3; // Increment when a schema change cannot be safely read by older app code.
const PZR_FORMAT='puzzlr-session',PZR_EXPORT_VERSION=1,MAX_IMPORT_BYTES=100*1024*1024;
const MAX_RENDER_EDGE=8192,MAX_RENDER_PIXELS=24*1024*1024;
const canvas=document.querySelector('#puzzleCanvas'), ctx=canvas.getContext('2d'), hitContext=document.createElement('canvas').getContext('2d'), stage=document.querySelector('#stage'), address=document.querySelector('#imageAddress'),cacheDebugPanel=document.querySelector('#cacheDebugPanel'),cacheDebugCanvas=document.querySelector('#cacheDebugCanvas'),cacheDebugInfo=document.querySelector('#cacheDebugInfo');
address.value=DEFAULT_IMAGE;
const themeMedia=matchMedia('(prefers-color-scheme: dark)');
function applyTheme(preference,save=true){const resolved=preference==='system'?(themeMedia.matches?'dark':'light'):preference;document.documentElement.dataset.theme=resolved;document.querySelector('#themeSelect').value=preference;if(save)try{localStorage.setItem('puzzlr-theme',preference)}catch{}if(layout)draw()}
let themePreference='system';try{themePreference=localStorage.getItem('puzzlr-theme')||'system'}catch{}applyTheme(themePreference,false);document.querySelector('#themeSelect').onchange=event=>{themePreference=event.target.value;applyTheme(themePreference)};const followSystemTheme=()=>{if(themePreference==='system')applyTheme('system',false)};if(themeMedia.addEventListener)themeMedia.addEventListener('change',followSystemTheme);else themeMedia.addListener(followSystemTheme);
try{glowEnabled=localStorage.getItem('puzzlr-glow')!=='off'}catch{}document.querySelector('#glowToggle').checked=glowEnabled;document.querySelector('#glowToggle').onchange=event=>{glowEnabled=event.target.checked;try{localStorage.setItem('puzzlr-glow',glowEnabled?'on':'off')}catch{}if(layout)draw()};
try{bevelEnabled=localStorage.getItem('puzzlr-bevel')!=='off'}catch{}document.querySelector('#bevelToggle').checked=bevelEnabled;document.querySelector('#bevelToggle').onchange=event=>{bevelEnabled=event.target.checked;try{localStorage.setItem('puzzlr-bevel',bevelEnabled?'on':'off')}catch{}if(layout){if(bevelEnabled&&pieces.length)buildBevelAtlases();else disposeBevelAtlases();invalidateRenderCaches();draw();scheduleCacheRefinement()}};
try{pieceOutlinesEnabled=localStorage.getItem('puzzlr-piece-outlines')==='on'}catch{}document.querySelector('#outlineToggle').checked=pieceOutlinesEnabled;document.querySelector('#outlineToggle').onchange=event=>{pieceOutlinesEnabled=event.target.checked;try{localStorage.setItem('puzzlr-piece-outlines',pieceOutlinesEnabled?'on':'off')}catch{}if(layout){invalidateRenderCaches();draw();scheduleCacheRefinement()}};
try{cacheDebugEnabled=localStorage.getItem('puzzlr-cache-debug')==='on'}catch{}document.querySelector('#cacheDebugToggle').checked=cacheDebugEnabled;cacheDebugPanel.hidden=!cacheDebugEnabled;document.querySelector('#cacheDebugToggle').onchange=event=>{cacheDebugEnabled=event.target.checked;cacheDebugPanel.hidden=!cacheDebugEnabled;try{localStorage.setItem('puzzlr-cache-debug',cacheDebugEnabled?'on':'off')}catch{}if(cacheDebugEnabled)updateCacheDebug()};
const optionsButtonElement=document.getElementById('optionsButton'),optionsMenuElement=document.getElementById('optionsMenu');function setOptionsOpen(open){optionsMenuElement.hidden=!open;optionsButtonElement.setAttribute('aria-expanded',String(open))}optionsButtonElement.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();setOptionsOpen(optionsMenuElement.hidden)});optionsMenuElement.addEventListener('click',event=>event.stopPropagation());document.addEventListener('click',event=>{if(!event.target.closest('.options'))setOptionsOpen(false)});document.addEventListener('keydown',event=>{if(event.key==='Escape')setOptionsOpen(false)});

function openSessionDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open('puzzlr-sessions',1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('sessions'))request.result.createObjectStore('sessions',{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function sessionRequest(mode,operation){const db=await openSessionDB();return new Promise((resolve,reject)=>{const tx=db.transaction('sessions',mode),request=operation(tx.objectStore('sessions'));request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close()})}
const getSession=id=>sessionRequest('readonly',store=>store.get(id));
const getSessions=()=>sessionRequest('readonly',store=>store.getAll());
const putSession=value=>sessionRequest('readwrite',store=>store.put(value));
const removeSession=id=>sessionRequest('readwrite',store=>store.delete(id));
async function captureRemoteImage(){if(imageBlob||!imageUrl||imageUrl.startsWith('blob:'))return imageBlob;try{const response=await fetch(imageUrl,{mode:'cors',referrerPolicy:'no-referrer'});if(response.ok)imageBlob=await response.blob()}catch{}return imageBlob}
async function blobToBase64(blob){const bytes=new Uint8Array(await blob.arrayBuffer());let binary='';for(let offset=0;offset<bytes.length;offset+=32768)binary+=String.fromCharCode(...bytes.subarray(offset,offset+32768));return btoa(binary)}
function base64ToBlob(value,type){const binary=atob(value),bytes=new Uint8Array(binary.length);for(let index=0;index<binary.length;index++)bytes[index]=binary.charCodeAt(index);return new Blob([bytes],{type:type||'application/octet-stream'})}
function safeExportName(value){return(value||'puzzlr-session').replace(/[<>:"/\\|?*\u0000-\u001f]/g,'-').replace(/[. ]+$/,'').slice(0,80)||'puzzlr-session'}
function createSessionId(){if(globalThis.crypto?.randomUUID)return crypto.randomUUID();return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,char=>{const value=Math.random()*16|0,bits=char==='x'?value:value&3|8;return bits.toString(16)})}
const defaultPuzzleName=id=>id.slice(0,8);
async function uniquePuzzleName(desired,excludeId=null){const base=(desired||'Puzzle').trim()||'Puzzle',names=(await getSessions()).filter(save=>save.id!==excludeId).map(save=>(save.name||'').toLocaleLowerCase());if(!names.includes(base.toLocaleLowerCase()))return base;let number=2;while(names.includes(`${base} ${number}`.toLocaleLowerCase()))number++;return`${base} ${number}`}
async function saveSession(silent=false){if(!gameStarted){if(!silent)alert('Start a puzzle before saving a session.');return false}const button=document.querySelector('#saveSession'),oldText=button.textContent;if(!silent)button.textContent='Saving…';try{await captureRemoteImage();const savedAt=Date.now();currentSessionId||=createSessionId();puzzleName=await uniquePuzzleName(puzzleName||defaultPuzzleName(currentSessionId),currentSessionId);const data={id:currentSessionId,version:SAVE_VERSION,name:puzzleName,savedAt,imageUrl:imageUrl.startsWith('blob:')?null:imageUrl,imageBlob,crop,level,rotationEnabled,moves,seconds,gameWon,groups:groups.map(group=>({ids:[...group.ids],dx:group.dx/layout.boardW,dy:group.dy/layout.boardH,rotation:group.rotation||0})),view:{zoom:view.zoom,panX:view.panX/layout.width,panY:view.panY/layout.height}};await putSession(data);sessionDirty=false;if(!silent){button.textContent='Saved ✓';setTimeout(()=>button.textContent=oldText,1400)}await refreshSessionList();return true}catch{if(!silent)button.textContent=oldText;alert('This browser could not save the session. Check that private browsing is off and device storage is available.');return false}}
function loadImagePromise(src){return new Promise((resolve,reject)=>{const next=new Image();next.referrerPolicy='no-referrer';next.onload=()=>resolve(next);next.onerror=reject;next.src=src})}
function compatibleSession(saved){if(!saved||typeof saved.version!=='number'||saved.version>SAVE_VERSION)return null;if(!saved.crop||!Array.isArray(saved.groups)||!saved.view)return null;return saved}
async function resumeSession(id){const saved=compatibleSession(await getSession(id));if(!saved)return alert('This save was created by an unsupported app version or is incomplete. It was left untouched.');clearInterval(timer);try{if(localUrl){URL.revokeObjectURL(localUrl);localUrl=null}imageBlob=saved.imageBlob||null;if(imageBlob){localUrl=URL.createObjectURL(imageBlob);imageUrl=localUrl}else imageUrl=saved.imageUrl||DEFAULT_IMAGE;image=await loadImagePromise(imageUrl);crop=saved.crop;level=Object.hasOwn(LEVELS,saved.level)?saved.level:'Medium';rotationEnabled=!!saved.rotationEnabled;document.querySelector('#allowRotation').checked=rotationEnabled;address.value=saved.imageUrl||'';document.querySelector('#cropWidth').value=Math.round(crop.sw/image.naturalWidth*100);document.querySelector('#cropHeight').value=Math.round(crop.sh/image.naturalHeight*100);const availableX=image.naturalWidth-crop.sw,availableY=image.naturalHeight-crop.sh;document.querySelector('#cropX').value=availableX>0?Math.round(crop.sx/availableX*200-100):0;document.querySelector('#cropY').value=availableY>0?Math.round(crop.sy/availableY*200-100):0;document.querySelector('#boardWidth').value=Math.round(crop.sw);document.querySelector('#boardHeight').value=Math.round(crop.sh);renderLevels();updateCropPreview();makePieces();fitLayout();if(bevelEnabled)buildBevelAtlases();else disposeBevelAtlases();groups=saved.groups.map(group=>({ids:group.ids.filter(id=>pieces[id]),dx:Number(group.dx||0)*layout.boardW,dy:Number(group.dy||0)*layout.boardH,rotation:Number(group.rotation||0)%4})).filter(group=>group.ids.length);moves=Number(saved.moves||0);seconds=Number(saved.seconds||0);gameWon=!!saved.gameWon;gameStarted=true;sessionDirty=false;currentSessionId=saved.id;puzzleName=saved.name||defaultPuzzleName(saved.id);document.querySelector('#puzzleName').value=puzzleName;view={zoom:Number(saved.view.zoom||1),panX:Number(saved.view.panX||0)*layout.width,panY:Number(saved.view.panY||0)*layout.height};document.querySelector('#boardZoom').value=Math.round(view.zoom*100);document.querySelector('#zoomValue').value=`${Math.round(view.zoom*100)}%`;document.querySelector('#moves').textContent=String(moves).padStart(2,'0');document.querySelector('#time').textContent=formatTime(seconds);updateProgress();document.querySelector('#setupOverlay').hidden=true;document.body.classList.remove('setupOpen');draw();if(!gameWon)timer=setInterval(()=>{seconds++;document.querySelector('#time').textContent=formatTime(seconds)},1000)}catch{alert('The saved session could not be restored. Its image or data may no longer be available.')}}
async function deleteSession(id){if(!confirm('Delete this saved session? This cannot be undone.'))return;await removeSession(id);await refreshSessionList()}
async function renameSession(id){const saved=await getSession(id);if(!saved)return;const entered=prompt('Enter a unique name for this puzzle session:',saved.name||defaultPuzzleName(id));if(entered===null)return;const desired=entered.trim();if(!desired)return alert('The session name cannot be empty.');const unique=await uniquePuzzleName(desired,id);if(unique!==desired)return alert('That name is already used by another saved puzzle.');saved.name=desired;saved.version=Math.max(saved.version||1,SAVE_VERSION);await putSession(saved);if(currentSessionId===id){puzzleName=desired;document.querySelector('#puzzleName').value=desired}await refreshSessionList()}
async function resetSession(id){const saved=compatibleSession(await getSession(id));if(!saved)return alert('This saved puzzle cannot be used as a template.');try{if(localUrl){URL.revokeObjectURL(localUrl);localUrl=null}imageBlob=saved.imageBlob||null;if(imageBlob){localUrl=URL.createObjectURL(imageBlob);imageUrl=localUrl}else imageUrl=saved.imageUrl||DEFAULT_IMAGE;image=await loadImagePromise(imageUrl);crop=saved.crop;level=Object.hasOwn(LEVELS,saved.level)?saved.level:'Medium';rotationEnabled=!!saved.rotationEnabled;document.querySelector('#allowRotation').checked=rotationEnabled;address.value=saved.imageUrl||'';document.querySelector('#cropWidth').value=Math.round(crop.sw/image.naturalWidth*100);document.querySelector('#cropHeight').value=Math.round(crop.sh/image.naturalHeight*100);const availableX=image.naturalWidth-crop.sw,availableY=image.naturalHeight-crop.sh;document.querySelector('#cropX').value=availableX>0?Math.round(crop.sx/availableX*200-100):0;document.querySelector('#cropY').value=availableY>0?Math.round(crop.sy/availableY*200-100):0;document.querySelector('#boardWidth').value=Math.round(crop.sw);document.querySelector('#boardHeight').value=Math.round(crop.sh);pendingSessionId=createSessionId();puzzleName=await uniquePuzzleName(`${saved.name||defaultPuzzleName(saved.id)} reset`);document.querySelector('#puzzleName').value=puzzleName;renderLevels();updateCropPreview();showPuzzleCreator()}catch{alert('This saved puzzle’s image could not be loaded for reset.')}}
async function exportSession(id){const saved=await getSession(id);if(!saved)return alert('That saved puzzle could not be found.');try{let embedded=saved.imageBlob||null;if(!embedded&&saved.imageUrl){const response=await fetch(saved.imageUrl,{mode:'cors',referrerPolicy:'no-referrer'});if(response.ok)embedded=await response.blob()}if(!embedded)throw new Error('image');const session={...saved,imageBlob:{type:embedded.type||'application/octet-stream',base64:await blobToBase64(embedded)}},payload={format:PZR_FORMAT,exportVersion:PZR_EXPORT_VERSION,exportedAt:new Date().toISOString(),session},file=new Blob([JSON.stringify(payload)],{type:'application/x-puzzlr'}),url=URL.createObjectURL(file),link=document.createElement('a');link.href=url;link.download=`${safeExportName(saved.name||defaultPuzzleName(saved.id))}.pzr`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch{alert('This session could not be exported because its image data is unavailable. Open the puzzle, save it again, and retry.')}}
function validImportedSession(saved){if(!compatibleSession(saved)||typeof saved.id!=='string'||!saved.id||!Object.hasOwn(LEVELS,saved.level))return false;if(!Number.isFinite(saved.crop.sx)||!Number.isFinite(saved.crop.sy)||!Number.isFinite(saved.crop.sw)||!Number.isFinite(saved.crop.sh)||saved.crop.sw<=0||saved.crop.sh<=0)return false;if(!saved.groups.every(group=>Array.isArray(group.ids)&&group.ids.every(id=>Number.isInteger(id)&&id>=0)&&Number.isFinite(Number(group.dx))&&Number.isFinite(Number(group.dy))&&Number.isFinite(Number(group.rotation||0))))return false;return Number.isFinite(Number(saved.view.zoom))&&Number.isFinite(Number(saved.view.panX))&&Number.isFinite(Number(saved.view.panY))}
async function importSession(file){if(!file)return;if(file.size>MAX_IMPORT_BYTES)return alert('That .pzr file is larger than the 100 MB import limit.');try{const payload=JSON.parse(await file.text());if(payload?.format!==PZR_FORMAT||payload.exportVersion!==PZR_EXPORT_VERSION)throw new Error('format');const saved=payload.session;if(!saved||typeof saved.version!=='number')throw new Error('format');if(saved.version>SAVE_VERSION)return alert(`This puzzle uses save version ${saved.version}, but this app supports up to version ${SAVE_VERSION}. Update the app before importing it.`);if(saved.imageBlob?.base64)saved.imageBlob=base64ToBlob(saved.imageBlob.base64,saved.imageBlob.type);else throw new Error('image');if(!validImportedSession(saved))throw new Error('data');const existing=await getSession(saved.id);if(existing&&!confirm(`A saved puzzle with this session ID already exists. Replace “${existing.name||defaultPuzzleName(existing.id)}”?`))return;saved.name=await uniquePuzzleName(saved.name||defaultPuzzleName(saved.id),saved.id);saved.savedAt=Date.now();await putSession(saved);await refreshSessionList();document.querySelector('#createPuzzlePanel').hidden=true;document.querySelector('#savedSessions').hidden=false;alert(`Imported “${saved.name}”.`)}catch(error){alert(error.message==='image'?'This .pzr file does not contain its puzzle image.':'This file is not a valid or compatible Puzzlr session.')}}
function savedCompletion(saved){if(saved.gameWon)return 100;if(!Array.isArray(saved.groups)||!saved.groups.length)return 0;const total=saved.groups.reduce((sum,group)=>sum+(Array.isArray(group.ids)?group.ids.length:0),0),largest=Math.max(0,...saved.groups.map(group=>Array.isArray(group.ids)?group.ids.length:0));return total?Math.round(largest/total*100):0}
function sessionRow(saved,isLast=false){const row=document.createElement('div');row.className=`sessionRow${isLast?' lastSessionRow':''}`;const status=saved.version>SAVE_VERSION?'Newer app version':`${savedCompletion(saved)}% complete · ${saved.moves||0} moves · ${new Date(saved.savedAt||0).toLocaleString()}`;const info=document.createElement('div'),title=document.createElement('strong'),detail=document.createElement('small'),actions=document.createElement('div');title.textContent=saved.name||defaultPuzzleName(saved.id);detail.textContent=status;info.append(title,detail);actions.className='sessionActions';actions.innerHTML='<button class="previewSaved">Preview</button><button class="resumeOne">Resume</button><button class="resetSession">Reset</button><button class="renameSession">Rename</button><button class="exportSession">Export</button><button class="deleteSession">Delete</button>';row.append(info,actions);bindSavedPreview(actions.querySelector('.previewSaved'),saved);actions.querySelector('.resumeOne').onclick=()=>resumeSession(saved.id);actions.querySelector('.resetSession').onclick=()=>resetSession(saved.id);actions.querySelector('.renameSession').onclick=()=>renameSession(saved.id);actions.querySelector('.exportSession').onclick=()=>exportSession(saved.id);actions.querySelector('.deleteSession').onclick=()=>deleteSession(saved.id);return row}
async function refreshSessionList(){try{const saves=(await getSessions()).sort((a,b)=>(b.savedAt||0)-(a.savedAt||0)),root=document.querySelector('#savedSessions'),last=document.querySelector('#lastSession'),list=document.querySelector('#sessionList'),previousTitle=document.querySelector('.previousTitle'),back=document.querySelector('#backToSessions');root.hidden=!saves.length;back.hidden=!saves.length;last.innerHTML='';list.innerHTML='';if(!saves.length){document.querySelector('#createPuzzlePanel').hidden=false;return saves}last.append(sessionRow(saves[0],true));previousTitle.hidden=saves.length<2;saves.slice(1).forEach(saved=>list.append(sessionRow(saved)));return saves}catch{document.querySelector('#savedSessions').hidden=true;document.querySelector('#backToSessions').hidden=true;document.querySelector('#createPuzzlePanel').hidden=false;return[]}}
function showPuzzleCreator(){document.querySelector('#savedSessions').hidden=true;document.querySelector('#createPuzzlePanel').hidden=false;requestAnimationFrame(()=>{updateCropPreview();document.querySelector('#puzzleName').focus()})}

function rand(seed){ const value=Math.sin(seed*999.91)*43758.5453; return value-Math.floor(value); }
function gridForLevel(){const size=LEVELS[level],ratio=crop?crop.sw/crop.sh:(image.naturalWidth/image.naturalHeight||1);return[Math.max(2,Math.round(size*Math.sqrt(ratio))),Math.max(2,Math.round(size/Math.sqrt(ratio)))]}
function edge(seed,sign){ return {sign, width:.36+rand(seed)*.14, depth:.20+rand(seed+3)*.075, lean:(rand(seed+8)-.5)*.12, neck:.48+rand(seed+12)*.16, crown:.82+rand(seed+16)*.14, shoulder:.055+rand(seed+21)*.045}; }
function makePieces(){
  const [cols,rows]=gridForLevel(), vertical=[], horizontal=[];
  for(let r=0;r<rows;r++){vertical[r]=[];for(let c=0;c<cols-1;c++)vertical[r][c]=edge(100+r*cols+c,rand(500+r*cols+c)>.5?1:-1)}
  for(let r=0;r<rows-1;r++){horizontal[r]=[];for(let c=0;c<cols;c++)horizontal[r][c]=edge(900+r*cols+c,rand(1200+r*cols+c)>.5?1:-1)}
  const mate=feature=>({...feature,sign:-feature.sign,lean:-feature.lean});
  pieces=[]; for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)pieces.push({id:r*cols+c,col:c,row:r,edges:{top:r?mate(horizontal[r-1][c]):null,right:c<cols-1?vertical[r][c]:null,bottom:r<rows-1?horizontal[r][c]:null,left:c?mate(vertical[r][c-1]):null}});
}
function fitLayout(){
  const width=stage.clientWidth,[cols,rows]=gridForLevel(),touchLayout=width<640||matchMedia('(pointer:coarse)').matches,imageRatio=crop?crop.sw/crop.sh:(image.naturalWidth/image.naturalHeight||cols/rows),stageRect=stage.getBoundingClientRect(),stageTop=window.scrollY+stageRect.top,workspaceBottom=window.scrollY+document.querySelector('.workspace').getBoundingClientRect().bottom,contentAfterStage=Math.max(0,workspaceBottom-(window.scrollY+stageRect.bottom)),availableHeight=window.innerHeight-stageTop-contentAfterStage,height=Math.max(1,availableHeight),mobile=width<640;
  const maxBoardW=touchLayout?width*.45:Math.min(width*.7,920),maxBoardH=touchLayout?height*.45:Math.min(height*.72,480);let boardW=maxBoardW,boardH=boardW/imageRatio;if(boardH>maxBoardH){boardH=maxBoardH;boardW=boardH*imageRatio}
  const boardX=(width-boardW)/2, boardY=(height-boardH)/2;
  layout={width,height,boardX,boardY,boardW,boardH,cellW:boardW/cols,cellH:boardH/rows,mobile:touchLayout};
  dpr=Math.min(window.devicePixelRatio||1,3); canvas.width=width*dpr;canvas.height=height*dpr;canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';
}
function scatter(){
  fitLayout();if(bevelEnabled)buildBevelAtlases();else disposeBevelAtlases();groups=pieces.map(piece=>({ids:[piece.id],dx:0,dy:0,rotation:0}));positionGroups(groups,true);
}
function groupBounds(group){const members=group.ids.map(id=>pieces[id]),minCol=Math.min(...members.map(piece=>piece.col)),maxCol=Math.max(...members.map(piece=>piece.col)),minRow=Math.min(...members.map(piece=>piece.row)),maxRow=Math.max(...members.map(piece=>piece.row));return{minCol,maxCol,minRow,maxRow,width:(maxCol-minCol+1)*layout.cellW,height:(maxRow-minRow+1)*layout.cellH}}
function groupCenter(group){const bounds=groupBounds(group);return{x:layout.boardX+(bounds.minCol+bounds.maxCol+1)*layout.cellW/2+group.dx,y:layout.boardY+(bounds.minRow+bounds.maxRow+1)*layout.cellH/2+group.dy}}
function rotatePoint(point,center,quarters){const angle=quarters*Math.PI/2,cos=Math.cos(angle),sin=Math.sin(angle),x=point.x-center.x,y=point.y-center.y;return{x:center.x+x*cos-y*sin,y:center.y+x*sin+y*cos}}
function groupIsOnBoard(group){const center=groupCenter(group);return group.ids.some(id=>{const piece=pieces[id],base=piecePosition(piece,group),point=rotatePoint({x:base.x+layout.cellW/2,y:base.y+layout.cellH/2},center,group.rotation||0);return point.x>=layout.boardX&&point.x<=layout.boardX+layout.boardW&&point.y>=layout.boardY&&point.y<=layout.boardY+layout.boardH})}
function positionGroups(list,randomizeRotation=false){const seed=Date.now()%100000,cx=layout.width/2,cy=layout.height/2,toWorld=(x,y)=>({x:(x-cx-view.panX)/view.zoom+cx,y:(y-cy-view.panY)/view.zoom+cy}),topLeft=toWorld(0,0),bottomRight=toWorld(layout.width,layout.height),visible={left:topLeft.x,top:topLeft.y,right:bottomRight.x,bottom:bottomRight.y},boardRight=layout.boardX+layout.boardW,boardBottom=layout.boardY+layout.boardH;
  list.forEach((group,index)=>{if(randomizeRotation&&rotationEnabled)group.rotation=Math.floor(rand(seed+index*19)*4);const bounds=groupBounds(group),turned=(group.rotation||0)%2===1,groupW=turned?bounds.height:bounds.width,groupH=turned?bounds.width:bounds.height,maxX=visible.right-groupW,maxY=visible.bottom-groupH;if(maxX<visible.left||maxY<visible.top)return;let chosen=null;for(let attempt=0;attempt<48;attempt++){const token=seed+index*101+attempt*13,x=visible.left+rand(token)*(maxX-visible.left),y=visible.top+rand(token+7)*(maxY-visible.top),overlapsBoard=x<boardRight&&x+groupW>layout.boardX&&y<boardBottom&&y+groupH>layout.boardY;if(!overlapsBoard){chosen={x,y};break}}if(!chosen)return;const baseCenterX=layout.boardX+(bounds.minCol+bounds.maxCol+1)*layout.cellW/2,baseCenterY=layout.boardY+(bounds.minRow+bounds.maxRow+1)*layout.cellH/2;group.dx=chosen.x+groupW/2-baseCenterX;group.dy=chosen.y+groupH/2-baseCenterY});hovered=null;draw()}
function reshuffleLoose(){positionGroups(groups.filter(group=>!groupIsOnBoard(group)));sessionDirty=true}
function addEdge(path,x1,y1,x2,y2,feature,side){
  if(!feature){path.lineTo(x2,y2);return} const horizontal=y1===y2, len=horizontal?x2-x1:y2-y1, dir=Math.sign(len), abs=Math.abs(len), unit=Math.min(layout.cellW,layout.cellH), mid=.5+feature.lean*(unit/abs), half=(feature.width*unit/2)/abs, depth=feature.depth*unit*feature.sign*side;
  const p=(fraction,off=0)=>horizontal?[x1+dir*abs*fraction,y1+off]:[x1+off,y1+dir*abs*fraction];
  const neck=half*feature.neck, crown=half*feature.crown, shoulder=depth*feature.shoulder;
  const a=p(mid-half), b=p(mid-half*.90,-shoulder), c=p(mid-neck*1.18,-shoulder), d=p(mid-neck,depth*.16);
  const e=p(mid-crown,depth*.42), f=p(mid-crown*.78,depth*.92), g=p(mid,depth);
  const h=p(mid+crown*.78,depth*.92), i=p(mid+crown,depth*.42), j=p(mid+neck,depth*.16);
  const k=p(mid+neck*1.18,-shoulder), l=p(mid+half*.90,-shoulder), m=p(mid+half);
  path.lineTo(...a);path.bezierCurveTo(...b,...c,...d);path.bezierCurveTo(...e,...f,...g);path.bezierCurveTo(...h,...i,...j);path.bezierCurveTo(...k,...l,...m);path.lineTo(x2,y2);
}
function piecePath(piece,x,y){
  const w=layout.cellW,h=layout.cellH,path=new Path2D();path.moveTo(x,y);addEdge(path,x,y,x+w,y,piece.edges.top,-1);addEdge(path,x+w,y,x+w,y+h,piece.edges.right,1);addEdge(path,x+w,y+h,x,y+h,piece.edges.bottom,1);addEdge(path,x,y+h,x,y,piece.edges.left,-1);path.closePath();return path;
}
function disposeBevelAtlases(){if(bevelAtlases)bevelAtlases.forEach(atlas=>{atlas.width=0;atlas.height=0});bevelAtlases=null;bevelGeneration++}
function buildBevelAtlases(){disposeBevelAtlases();if(!pieces.length||!layout)return;const limit=2048,aspect=layout.boardW/layout.boardH,width=Math.max(1,Math.round(aspect>=1?limit:limit*aspect)),height=Math.max(1,Math.round(aspect>=1?limit/aspect:limit)),scale=width/layout.boardW,stroke=(style,lineWidth,path,c,dx,dy)=>{c.save();c.translate(dx,dy);c.strokeStyle=style;c.lineWidth=lineWidth;c.stroke(path);c.restore()};bevelAtlases=Array.from({length:4},(_,rotation)=>{const atlas=document.createElement('canvas');atlas.width=width;atlas.height=height;const c=atlas.getContext('2d');clearCanvas(c);c.setTransform(scale,0,0,scale,0,0);c.lineCap='round';c.lineJoin='round';const angle=-rotation*Math.PI/2,screenLight=-Math.SQRT1_2,lightX=screenLight*Math.cos(angle)-screenLight*Math.sin(angle),lightY=screenLight*Math.sin(angle)+screenLight*Math.cos(angle),shift=.7/scale;for(const piece of pieces){const path=piecePath(piece,piece.col*layout.cellW,piece.row*layout.cellH);c.save();c.clip(path);stroke('rgba(45,31,22,.22)',3.2/scale,path,c,lightX*shift,lightY*shift);stroke('rgba(255,232,196,.13)',2.2/scale,path,c,-lightX*shift,-lightY*shift);c.restore()}return atlas});bevelGeneration++}
function groupFor(id){return groups.find(group=>group.ids.includes(id))}
function piecePosition(piece,group){return {x:layout.boardX+piece.col*layout.cellW+group.dx,y:layout.boardY+piece.row*layout.cellH+group.dy}}
function invalidateRenderCaches(){cacheGeneration++;staticFrame=null;groups.forEach(group=>delete group.bitmapCache)}
function clearCanvas(target){target.setTransform(1,0,0,1,0,0);target.globalAlpha=1;target.globalCompositeOperation='copy';target.shadowColor='rgba(0,0,0,0)';target.shadowBlur=0;target.shadowOffsetX=0;target.shadowOffsetY=0;target.filter='none';target.clearRect(0,0,target.canvas.width,target.canvas.height);target.globalCompositeOperation='source-over'}
function updateCacheDebug(status=navigationFrame?'ACTIVE':'SETTLED — showing last cache'){if(!cacheDebugEnabled)return;if(navigationFrame){const maxW=640,scale=Math.min(1,maxW/navigationFrame.width),w=Math.max(1,Math.round(navigationFrame.width*scale)),h=Math.max(1,Math.round(navigationFrame.height*scale));if(cacheDebugCanvas.width!==w||cacheDebugCanvas.height!==h){cacheDebugCanvas.width=w;cacheDebugCanvas.height=h}const debugContext=cacheDebugCanvas.getContext('2d');clearCanvas(debugContext);debugContext.imageSmoothingEnabled=true;debugContext.imageSmoothingQuality='high';debugContext.drawImage(navigationFrame,0,0,w,h)}const base=navigationBase?.zoom,cachePixels=groups.reduce((sum,group)=>sum+(group.bitmapCache?.bitmap?.width||0)*(group.bitmapCache?.bitmap?.height||0)+(group.bitmapCache?.bevelBitmap?.width||0)*(group.bitmapCache?.bevelBitmap?.height||0),0),cacheMB=cachePixels*4/1048576;cacheDebugInfo.value=`${status} · source ${navigationFrame?`${navigationFrame.width}×${navigationFrame.height}`:'retained preview'} · base ${base?Math.round(base*100)+'%':'—'} · current ${Math.round(view.zoom*100)}% · overscan ${navigationBase?Math.round(navigationBase.overscan):'—'} CSS px · capture ${renderMetrics.captureMs.toFixed(1)} ms · nav draw ${renderMetrics.navigationDrawMs.toFixed(1)} ms · refine ${renderMetrics.cacheBuildMs.toFixed(1)} ms · queue ${renderMetrics.cacheQueue} · cache ${cacheMB.toFixed(1)} MB`;cacheDebugInfo.textContent=cacheDebugInfo.value}
function groupCacheSpec(group){const bounds=groupBounds(group),pad=Math.ceil(Math.min(layout.cellW,layout.cellH)*.38+3),w=bounds.width+pad*2,h=bounds.height+pad*2,source=crop||{sx:0,sy:0,sw:image.naturalWidth,sh:image.naturalHeight},sourceScale=Math.min(source.sw/layout.boardW,source.sh/layout.boardH),pixelBudgetScale=Math.sqrt(MAX_RENDER_PIXELS/(w*h)),scale=Math.max(1,Math.min(sourceScale,MAX_RENDER_EDGE/w,MAX_RENDER_EDGE/h,pixelBudgetScale)),atlas=bevelEnabled&&bevelAtlases?.[0],atlasScale=atlas?Math.min(atlas.width/layout.boardW,atlas.height/layout.boardH):0,bevelScale=atlas?Math.max(1,Math.min(atlasScale,MAX_RENDER_EDGE/w,MAX_RENDER_EDGE/h,pixelBudgetScale)):0,bevelKey=atlas?`${bevelGeneration}:${group.rotation||0}:${bevelScale.toFixed(3)}`:'off';return{bounds,pad,w,h,source,scale,bevelScale,key:`${cacheGeneration}:${group.ids.join(',')}:${layout.cellW}:${layout.cellH}:${scale.toFixed(3)}:${bevelKey}`}}
function paintPieceIntoBitmap(c,id,spec){const{bounds,pad,source}=spec,piece=pieces[id],x=pad+(piece.col-bounds.minCol)*layout.cellW,y=pad+(piece.row-bounds.minRow)*layout.cellH,path=piecePath(piece,x,y);c.save();c.clip(path);c.drawImage(image,source.sx,source.sy,source.sw,source.sh,x-piece.col*layout.cellW,y-piece.row*layout.cellH,layout.boardW,layout.boardH);c.restore()}
function paintPieceBevel(c,id,spec,rotation=0){const atlas=bevelAtlases?.[((rotation%4)+4)%4];if(!atlas)return;const{bounds,pad}=spec,piece=pieces[id],x=pad+(piece.col-bounds.minCol)*layout.cellW,y=pad+(piece.row-bounds.minRow)*layout.cellH,path=piecePath(piece,x,y);c.save();c.clip(path);c.drawImage(atlas,0,0,atlas.width,atlas.height,x-piece.col*layout.cellW,y-piece.row*layout.cellH,layout.boardW,layout.boardH);c.restore()}
function createGroupBitmapBuilder(group,spec=groupCacheSpec(group)){const{w,h,scale,bevelScale}=spec,bitmap=document.createElement('canvas');bitmap.width=Math.ceil(w*scale);bitmap.height=Math.ceil(h*scale);const c=bitmap.getContext('2d');clearCanvas(c);c.setTransform(scale,0,0,scale,0,0);c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';let bevelBitmap=null,bc=null;if(bevelScale){bevelBitmap=document.createElement('canvas');bevelBitmap.width=Math.ceil(w*bevelScale);bevelBitmap.height=Math.ceil(h*bevelScale);bc=bevelBitmap.getContext('2d');clearCanvas(bc);bc.setTransform(bevelScale,0,0,bevelScale,0,0);bc.imageSmoothingEnabled=true;bc.imageSmoothingQuality='high'}return{group,spec,bitmap,c,bevelBitmap,bc,index:0,buildMs:0}}
function releaseGroupBitmapBuilder(builder){if(!builder)return;builder.bitmap.width=0;builder.bitmap.height=0;if(builder.bevelBitmap){builder.bevelBitmap.width=0;builder.bevelBitmap.height=0}}
function finishGroupBitmapBuilder(builder){const{spec,bitmap,bevelBitmap}=builder;renderMetrics.cacheBuildMs=builder.buildMs;return{key:spec.key,bitmap,bevelBitmap,pad:spec.pad,bounds:spec.bounds,w:spec.w,h:spec.h}}
function buildGroupBitmap(group,spec=groupCacheSpec(group)){const builder=createGroupBitmapBuilder(group,spec),started=performance.now();group.ids.forEach(id=>{paintPieceIntoBitmap(builder.c,id,spec);if(builder.bc)paintPieceBevel(builder.bc,id,spec,group.rotation||0)});builder.buildMs=performance.now()-started;return finishGroupBitmapBuilder(builder)}
function groupBitmap(group){return group.bitmapCache||(group.bitmapCache=buildGroupBitmap(group))}
function cancelCacheRefinement(){clearTimeout(cacheRefineTimer);cacheRefineTimer=null;if(cacheRefineWorkHandle!==null){if(cacheRefineWorkKind==='idle'&&'cancelIdleCallback'in window)cancelIdleCallback(cacheRefineWorkHandle);else cancelAnimationFrame(cacheRefineWorkHandle)}cacheRefineWorkHandle=null;cacheRefineWorkKind=null;releaseGroupBitmapBuilder(cacheRefineBuilder);cacheRefineBuilder=null;renderMetrics.cacheQueue=0;cacheRefineToken++}
function queueCacheRefineStep(step){if('requestIdleCallback'in window){cacheRefineWorkKind='idle';cacheRefineWorkHandle=requestIdleCallback(deadline=>{cacheRefineWorkHandle=null;cacheRefineWorkKind=null;step(deadline)},{timeout:80})}else{cacheRefineWorkKind='frame';cacheRefineWorkHandle=requestAnimationFrame(()=>{cacheRefineWorkHandle=null;cacheRefineWorkKind=null;step()})}}
function navigationIsActive(){return!!navigationFrame||!!active?.panning||!!pinchGesture}
function requestNavigationDraw(){if(navigationDrawFrame===null)navigationDrawFrame=requestAnimationFrame(time=>{navigationDrawFrame=null;updateCacheDebug();draw(time)})}
function cancelNavigationDraw(){if(navigationDrawFrame!==null)cancelAnimationFrame(navigationDrawFrame);navigationDrawFrame=null}
function cacheRefinePriority(group){const center=groupCenter(group),screenX=(center.x-layout.width/2)*view.zoom+layout.width/2+view.panX,screenY=(center.y-layout.height/2)*view.zoom+layout.height/2+view.panY,dx=Math.max(0,-screenX,screenX-layout.width),dy=Math.max(0,-screenY,screenY-layout.height),outside=Math.hypot(dx,dy);return(groupIsOnBoard(group)?-1e7:0)+outside}
function scheduleCacheRefinement(){cancelCacheRefinement();const token=cacheRefineToken;cacheRefineTimer=setTimeout(()=>{cacheRefineTimer=null;if(token!==cacheRefineToken||navigationIsActive())return;const queue=[...groups].sort((a,b)=>cacheRefinePriority(a)-cacheRefinePriority(b));renderMetrics.cacheQueue=queue.length;const abort=()=>token!==cacheRefineToken||navigationIsActive();const step=deadline=>{if(abort())return;const started=performance.now();let completed=false,didWork=false;const hasBudget=()=>!didWork||(deadline?.timeRemaining?deadline.timeRemaining()>3:performance.now()-started<6);while((cacheRefineBuilder||queue.length)&&hasBudget()){if(abort()){releaseGroupBitmapBuilder(cacheRefineBuilder);cacheRefineBuilder=null;return}if(!cacheRefineBuilder){const group=queue.shift();renderMetrics.cacheQueue=queue.length;if(!groups.includes(group))continue;const spec=groupCacheSpec(group);if(group.bitmapCache?.key===spec.key)continue;cacheRefineBuilder=createGroupBitmapBuilder(group,spec)}const builder=cacheRefineBuilder,id=builder.group.ids[builder.index++],pieceStarted=performance.now();paintPieceIntoBitmap(builder.c,id,builder.spec);if(builder.bc)paintPieceBevel(builder.bc,id,builder.spec,builder.group.rotation||0);builder.buildMs+=performance.now()-pieceStarted;didWork=true;if(builder.index>=builder.group.ids.length){if(groups.includes(builder.group)&&!abort())builder.group.bitmapCache=finishGroupBitmapBuilder(builder);else releaseGroupBitmapBuilder(builder);cacheRefineBuilder=null;completed=true}}if(completed)draw();if(cacheRefineBuilder||queue.length)queueCacheRefineStep(step);else renderMetrics.cacheQueue=0};queueCacheRefineStep(step)},100)}
function strokeGroup(target,group,color,screenWidth){const center=groupCenter(group);target.save();target.translate(center.x,center.y);target.rotate((group.rotation||0)*Math.PI/2);target.translate(-center.x,-center.y);target.strokeStyle=color;target.lineWidth=screenWidth/view.zoom;target.lineJoin='round';group.ids.forEach(id=>{const piece=pieces[id],pos=piecePosition(piece,group);target.stroke(piecePath(piece,pos.x,pos.y))});target.restore()}
function paintGroup(target,group,lifted=false,highlighted=false,renderOutline=true){const cached=groupBitmap(group),center=groupCenter(group),x=layout.boardX+cached.bounds.minCol*layout.cellW+group.dx-cached.pad,y=layout.boardY+cached.bounds.minRow*layout.cellH+group.dy-cached.pad;target.save();target.translate(center.x,center.y);target.rotate((group.rotation||0)*Math.PI/2);target.translate(-center.x,-center.y);if(glowEnabled&&!completionShadowsDisabled){target.shadowColor='rgb(0,0,0)';target.shadowBlur=lifted?20:8;target.shadowOffsetX=lifted?5:3;target.shadowOffsetY=lifted?7:4}target.drawImage(cached.bitmap,x,y,cached.w,cached.h);target.shadowColor='rgba(0,0,0,0)';target.shadowBlur=0;target.shadowOffsetX=0;target.shadowOffsetY=0;if(cached.bevelBitmap)target.drawImage(cached.bevelBitmap,x,y,cached.w,cached.h);target.restore();if(renderOutline){if(pieceOutlinesEnabled)strokeGroup(target,group,'rgba(0,0,0,.88)',1.25);if(highlighted)strokeGroup(target,group,'#ee5b32',2.5)}}
function wrapTipText(target,text,maxWidth){const words=text.split(' '),lines=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(line&&target.measureText(next).width>maxWidth){lines.push(line);line=word}else line=next}if(line)lines.push(line);return lines}
function paintAssemblyTips(target){const {boardX,boardY,boardW,boardH}=layout,padding=Math.max(7,Math.min(12,boardW*.025)),maxWidth=boardW-padding*2,tips=['Matching edges of puzzle pieces snap together and move as a group.',...(rotationEnabled?['Click or tap a piece without dragging to rotate it.']:[]),'Drag empty space to pan. Scroll or pinch to zoom.','RESHUFFLE gathers all pieces and groups outside this area into the current view.','Disable shadows from the ⚙ menu to improve performance.'];target.save();target.beginPath();target.rect(boardX,boardY,boardW,boardH);target.clip();let fontSize=Math.max(6,Math.min(9,boardW/36)),lineHeight,wrapped,headerHeight,totalHeight;do{target.font=`${fontSize}px Arial`;lineHeight=fontSize+2.5;wrapped=tips.map(tip=>wrapTipText(target,tip,maxWidth));headerHeight=lineHeight+2;totalHeight=headerHeight+wrapped.reduce((sum,lines)=>sum+lines.length,0)*lineHeight+(wrapped.length-1)*2;if(totalHeight<=boardH-32-padding||fontSize<=4.75)break;fontSize-=.5}while(true);let y=Math.max(boardY+24,boardY+boardH-padding-totalHeight);target.fillStyle='rgba(67,73,69,.82)';target.font=`700 ${fontSize+1}px Arial`;target.fillText('TIPS:',boardX+padding,y+fontSize+1);y+=headerHeight;target.font=`${fontSize}px Arial`;wrapped.forEach(lines=>{for(const line of lines){target.fillText(line,boardX+padding,y+fontSize);y+=lineHeight}y+=2});target.restore()}
function paintScene(target,excluded=null,overscan=0,renderOutlines=true){const {width,height,boardX,boardY,boardW,boardH}=layout;clearCanvas(target);target.setTransform(dpr,0,0,dpr,0,0);target.translate(overscan,overscan);target.save();target.translate(width/2+view.panX,height/2+view.panY);target.scale(view.zoom,view.zoom);target.translate(-width/2,-height/2);target.fillStyle='#e7e1d4';target.fillRect(-overscan,-overscan,width+overscan*2,height+overscan*2);target.save();target.setLineDash([5,6]);target.strokeStyle='#aaa89e';target.lineWidth=1.5;target.strokeRect(boardX,boardY,boardW,boardH);target.restore();target.fillStyle='#777b75';target.font='700 9px Arial';target.fillText('LOOSE PIECES HERE',boardX+8,boardY-7);target.fillText('ASSEMBLE HERE',boardX+8,boardY+16);paintAssemblyTips(target);if(previewing){target.globalAlpha=.92;const source=crop||{sx:0,sy:0,sw:image.naturalWidth,sh:image.naturalHeight};target.drawImage(image,source.sx,source.sy,source.sw,source.sh,boardX,boardY,boardW,boardH)}else groups.forEach(group=>{if(group!==excluded)paintGroup(target,group,false,group===hovered,renderOutlines)});target.restore()}
function captureStaticFrame(excluded){staticFrame=document.createElement('canvas');staticFrame.width=canvas.width;staticFrame.height=canvas.height;paintScene(staticFrame.getContext('2d'),excluded)}
function beginNavigation(excluded=null){cancelCacheRefinement();clearTimeout(navigationTimer);navigationTimer=null;if(navigationFrame)return;const started=performance.now();navigationExcluded=excluded;const maxPadX=Math.max(0,(4096/dpr-layout.width)/2),maxPadY=Math.max(0,(4096/dpr-layout.height)/2),overscanFactor=layout.mobile?.6:.65,overscan=Math.min(Math.max(layout.width,layout.height)*overscanFactor,maxPadX,maxPadY);navigationFrame=document.createElement('canvas');navigationFrame.width=Math.ceil((layout.width+overscan*2)*dpr);navigationFrame.height=Math.ceil((layout.height+overscan*2)*dpr);paintScene(navigationFrame.getContext('2d'),excluded,overscan,false);navigationBase={...view,overscan};renderMetrics.captureMs=performance.now()-started;updateCacheDebug()}
function paintNavigationFrame(){const started=performance.now(),{width,height}=layout,ratio=view.zoom/navigationBase.zoom,cx=width/2,cy=height/2,pad=navigationBase.overscan,destX=cx+view.panX-ratio*navigationBase.panX-ratio*(cx+pad),destY=cy+view.panY-ratio*navigationBase.panY-ratio*(cy+pad),destW=ratio*(width+pad*2),destH=ratio*(height+pad*2),left=Math.max(0,destX),top=Math.max(0,destY),right=Math.min(width,destX+destW),bottom=Math.min(height,destY+destH);if(right>left&&bottom>top){const sx=(left-destX)/destW*navigationFrame.width,sy=(top-destY)/destH*navigationFrame.height,sw=(right-left)/destW*navigationFrame.width,sh=(bottom-top)/destH*navigationFrame.height;ctx.drawImage(navigationFrame,sx,sy,sw,sh,left,top,right-left,bottom-top)}renderMetrics.navigationDrawMs=performance.now()-started}
function settleNavigation(){clearTimeout(navigationTimer);navigationTimer=setTimeout(()=>{cancelNavigationDraw();updateCacheDebug('SETTLED — showing last cache');navigationFrame=null;navigationBase=null;navigationExcluded=null;draw();scheduleCacheRefinement()},100)}
function edgePanSpeed(position,size,zone){if(position<zone)return-Math.pow((zone-position)/zone,1.35);if(position>size-zone)return Math.pow((position-(size-zone))/zone,1.35);return 0}
function stopEdgePan(){if(edgePanFrame)cancelAnimationFrame(edgePanFrame);edgePanFrame=null;edgePanLastTime=0}
function runEdgePan(time){edgePanFrame=null;if(!active?.group||!active.screen)return;const zone=Math.min(90,Math.max(54,Math.min(layout.width,layout.height)*.13)),vx=edgePanSpeed(active.screen.x,layout.width,zone),vy=edgePanSpeed(active.screen.y,layout.height,zone);if(vx||vy){if(!navigationFrame)beginNavigation(active.group);const elapsed=edgePanLastTime?Math.min(32,time-edgePanLastTime):16,maxSpeed=layout.mobile?720:900,panX=-vx*maxSpeed*elapsed/1000,panY=-vy*maxSpeed*elapsed/1000;view.panX+=panX;view.panY+=panY;active.group.dx-=panX/view.zoom;active.group.dy-=panY/view.zoom;active.last=pointerFromScreen(active.screen);active.moved=true;if(navigationBase&&(Math.abs(view.panX-navigationBase.panX)>navigationBase.overscan*.6||Math.abs(view.panY-navigationBase.panY)>navigationBase.overscan*.6)){navigationFrame=null;navigationBase=null;navigationExcluded=null;beginNavigation(active.group)}requestNavigationDraw()}edgePanLastTime=time;edgePanFrame=requestAnimationFrame(runEdgePan)}
function startEdgePan(){if(!edgePanFrame){edgePanLastTime=0;edgePanFrame=requestAnimationFrame(runEdgePan)}}
function triggerVictoryRipple(point){rippleOrigin=point;rippleStartedAt=performance.now();winStartedAt=rippleStartedAt;if(winAnimationFrame)cancelAnimationFrame(winAnimationFrame);winAnimationFrame=null;draw(rippleStartedAt)}
function paintVictoryRippleScene(now){const elapsed=now-rippleStartedAt,duration=1100;if(elapsed>=duration||matchMedia('(prefers-reduced-motion: reduce)').matches){rippleStartedAt=0;paintScene(ctx);return false}const group=groups[0],cached=groupBitmap(group),center=groupCenter(group),origin=rotatePoint(rippleOrigin,center,-(group.rotation||0)),baseX=layout.boardX+cached.bounds.minCol*layout.cellW+group.dx-cached.pad,baseY=layout.boardY+cached.bounds.minRow*layout.cellH+group.dy-cached.pad,maxDistance=Math.hypot(layout.boardW,layout.boardH),amplitude=Math.min(layout.cellW,layout.cellH)*.12,drawPieceShadows=glowEnabled&&!completionShadowsDisabled&&pieces.length<300,{width,height}=layout;paintScene(ctx,group);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.save();ctx.translate(width/2+view.panX,height/2+view.panY);ctx.scale(view.zoom,view.zoom);ctx.translate(-width/2,-height/2);ctx.translate(center.x,center.y);ctx.rotate((group.rotation||0)*Math.PI/2);ctx.translate(-center.x,-center.y);group.ids.forEach(id=>{const piece=pieces[id],pos=piecePosition(piece,group),pieceCenter={x:pos.x+layout.cellW/2,y:pos.y+layout.cellH/2},dx=pieceCenter.x-origin.x,dy=pieceCenter.y-origin.y,distance=Math.hypot(dx,dy),local=elapsed-distance/maxDistance*420,impulse=local>0&&local<650?Math.sin(local/95*Math.PI)*Math.exp(-local/330):0,lift=Math.max(0,impulse),radial=distance?1/distance:0,offsetX=dx*radial*amplitude*impulse,offsetY=dy*radial*amplitude*impulse-amplitude*.55*lift,path=piecePath(piece,pos.x,pos.y);ctx.save();ctx.translate(offsetX,offsetY);if(drawPieceShadows&&lift>.03){ctx.shadowColor='rgba(0,0,0,.55)';ctx.shadowBlur=10*lift;ctx.shadowOffsetX=2*lift;ctx.shadowOffsetY=5*lift;ctx.fillStyle='rgba(0,0,0,.015)';ctx.fill(path);ctx.shadowColor='rgba(0,0,0,0)'}ctx.clip(path);ctx.drawImage(cached.bitmap,baseX,baseY,cached.w,cached.h);ctx.restore();if(pieceOutlinesEnabled){ctx.save();ctx.translate(offsetX,offsetY);ctx.strokeStyle='rgba(0,0,0,.88)';ctx.lineWidth=1.25/view.zoom;ctx.stroke(path);ctx.restore()}});ctx.restore();return true}
function paintVictoryLighting(now){const elapsed=Math.max(0,now-winStartedAt),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,progress=reduced?1:Math.min(1,elapsed/2600),pulse=reduced?.24:Math.sin(Math.min(1,elapsed/900)*Math.PI)*.34+.1,{width,height,boardX,boardY,boardW,boardH}=layout,cx=width/2,cy=height/2;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.save();ctx.translate(cx+view.panX,cy+view.panY);ctx.scale(view.zoom,view.zoom);ctx.translate(-cx,-cy);ctx.beginPath();ctx.rect(boardX,boardY,boardW,boardH);ctx.clip();ctx.globalCompositeOperation='screen';const glow=ctx.createRadialGradient(boardX+boardW/2,boardY+boardH/2,0,boardX+boardW/2,boardY+boardH/2,Math.max(boardW,boardH)*.7);glow.addColorStop(0,`rgba(255,238,170,${pulse})`);glow.addColorStop(.55,`rgba(255,188,75,${pulse*.3})`);glow.addColorStop(1,'rgba(255,160,50,0)');ctx.fillStyle=glow;ctx.fillRect(boardX,boardY,boardW,boardH);if(!reduced&&progress<1){const sweepX=boardX-boardW*.35+boardW*1.7*progress,sweep=ctx.createLinearGradient(sweepX-boardW*.22,0,sweepX+boardW*.22,0);sweep.addColorStop(0,'rgba(255,245,205,0)');sweep.addColorStop(.5,'rgba(255,245,205,.52)');sweep.addColorStop(1,'rgba(255,245,205,0)');ctx.fillStyle=sweep;ctx.fillRect(boardX,boardY,boardW,boardH)}ctx.restore();ctx.setTransform(dpr,0,0,dpr,0,0);ctx.save();ctx.translate(cx+view.panX,cy+view.panY);ctx.scale(view.zoom,view.zoom);ctx.translate(-cx,-cy);ctx.strokeStyle=`rgba(255,192,74,${.35+pulse})`;ctx.lineWidth=3/view.zoom;ctx.shadowColor='rgba(255,177,58,.9)';ctx.shadowBlur=18;ctx.strokeRect(boardX,boardY,boardW,boardH);ctx.restore();return!reduced&&elapsed<2600}
function draw(now=performance.now()){
  const {width,height}=layout;if(navigationFrame&&navigationBase){const cx=width/2,cy=height/2;clearCanvas(ctx);ctx.setTransform(dpr,0,0,dpr,0,0);paintNavigationFrame();ctx.save();ctx.translate(cx+view.panX,cy+view.panY);ctx.scale(view.zoom,view.zoom);ctx.translate(-cx,-cy);groups.forEach(group=>{if(group===navigationExcluded)return;if(pieceOutlinesEnabled)strokeGroup(ctx,group,'rgba(0,0,0,.88)',1.25);if(group===hovered)strokeGroup(ctx,group,'#ee5b32',2.5)});if(navigationExcluded)paintGroup(ctx,navigationExcluded,true,true);ctx.restore()}else if(active?.group&&staticFrame){clearCanvas(ctx);ctx.drawImage(staticFrame,0,0);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.save();ctx.translate(width/2+view.panX,height/2+view.panY);ctx.scale(view.zoom,view.zoom);ctx.translate(-width/2,-height/2);paintGroup(ctx,active.group,true,true);ctx.restore()}else if(gameWon&&rippleStartedAt)paintVictoryRippleScene(now);else paintScene(ctx);let continueWin=false;if(gameWon){continueWin=paintVictoryLighting(now)||rippleStartedAt>0;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';const titleSize=Math.max(38,Math.min(78,width*.075));ctx.font=`italic ${titleSize}px Georgia`;ctx.lineJoin='round';ctx.lineWidth=Math.max(5,titleSize*.1);ctx.strokeStyle='rgba(255,255,255,.96)';ctx.strokeText('Beautifully done.',width/2,height/2-18);ctx.fillStyle='#18201d';ctx.fillText('Beautifully done.',width/2,height/2-18);ctx.font='700 14px Arial';ctx.lineWidth=4;const result=`${moves} moves · ${formatTime(seconds)}`;ctx.strokeText(result,width/2,height/2+42);ctx.fillStyle='#ee5b32';ctx.fillText(result,width/2,height/2+42);ctx.restore()}if(continueWin&&!winAnimationFrame)winAnimationFrame=requestAnimationFrame(t=>{winAnimationFrame=null;draw(t)})
}
function screenPointer(event){const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*layout.width/rect.width,y:(event.clientY-rect.top)*layout.height/rect.height}}
function pointerFromScreen(point){const cx=layout.width/2,cy=layout.height/2;return{x:(point.x-cx-view.panX)/view.zoom+cx,y:(point.y-cy-view.panY)/view.zoom+cy}}
function pointer(event){return pointerFromScreen(screenPointer(event))}
function hitTest(point){const pad=Math.min(layout.cellW,layout.cellH)*.3;for(let g=groups.length-1;g>=0;g--){const group=groups[g],center=groupCenter(group),testPoint=rotatePoint(point,center,-(group.rotation||0));for(let p=group.ids.length-1;p>=0;p--){const piece=pieces[group.ids[p]],pos=piecePosition(piece,group);if(testPoint.x<pos.x-pad||testPoint.x>pos.x+layout.cellW+pad||testPoint.y<pos.y-pad||testPoint.y>pos.y+layout.cellH+pad)continue;if(hitContext.isPointInPath(piecePath(piece,pos.x,pos.y),testPoint.x,testPoint.y))return group}}return null}
function adjacent(a,b){const pa=pieces[a],pb=pieces[b];return Math.abs(pa.col-pb.col)+Math.abs(pa.row-pb.row)===1}
function rotatedPieceCenter(group,id){const piece=pieces[id],pos=piecePosition(piece,group),center=groupCenter(group);return rotatePoint({x:pos.x+layout.cellW/2,y:pos.y+layout.cellH/2},center,group.rotation||0)}
function tryLocks(moving){
  let merged=true;
  while(merged){merged=false;for(const other of [...groups]){if(other===moving||(other.rotation||0)!==(moving.rotation||0))continue;let snap=null;for(const a of moving.ids)for(const b of other.ids){if(!adjacent(a,b))continue;const pa=pieces[a],pb=pieces[b],from=rotatedPieceCenter(moving,a),to=rotatedPieceCenter(other,b),angle=(moving.rotation||0)*Math.PI/2,dx=(pa.col-pb.col)*layout.cellW,dy=(pa.row-pb.row)*layout.cellH,expected={x:dx*Math.cos(angle)-dy*Math.sin(angle),y:dx*Math.sin(angle)+dy*Math.cos(angle)},error={x:to.x+expected.x-from.x,y:to.y+expected.y-from.y},distance=Math.hypot(error.x,error.y);if(!snap||distance<snap.distance)snap={...error,distance}}if(snap&&snap.distance<Math.min(layout.cellW,layout.cellH)*.3){moving.dx+=snap.x;moving.dy+=snap.y;const anchorId=moving.ids[0],anchorBefore=rotatedPieceCenter(moving,anchorId);moving.ids.push(...other.ids);const anchorAfter=rotatedPieceCenter(moving,anchorId);moving.dx+=anchorBefore.x-anchorAfter.x;moving.dy+=anchorBefore.y-anchorAfter.y;groups.splice(groups.indexOf(other),1);delete moving.bitmapCache;merged=true;break}}}
  return moving.ids.length===pieces.length;
}
canvas.addEventListener('pointerdown',event=>{event.preventDefault();if(previewing||pinchGesture)return;const point=pointer(event),screen=screenPointer(event),group=hitTest(point);cancelCacheRefinement();if(gameWon&&group){triggerVictoryRipple(point);return}if(group){groups.splice(groups.indexOf(group),1);groups.push(group);hovered=null;captureStaticFrame(group);active={group,last:point,start:screen,screen,moved:false};startEdgePan()}else{beginNavigation();active={panning:true,last:screen,start:screen,moved:false}}canvas.setPointerCapture(event.pointerId);draw()});
canvas.addEventListener('pointermove',event=>{if(pinchGesture)return;if(!active){const point=pointer(event),next=hitTest(point);canvas.style.cursor=next?'grab':'move';if(next!==hovered){hovered=next;draw()}return}event.preventDefault();const screen=screenPointer(event);if(Math.hypot(screen.x-active.start.x,screen.y-active.start.y)>5)active.moved=true;if(active.panning){view.panX+=screen.x-active.last.x;view.panY+=screen.y-active.last.y;active.last=screen}else{const point=pointerFromScreen(screen);active.group.dx+=point.x-active.last.x;active.group.dy+=point.y-active.last.y;active.last=point;active.screen=screen}requestNavigationDraw()});
canvas.addEventListener('pointerup',event=>{if(pinchGesture)return;if(!active)return;cancelNavigationDraw();stopEdgePan();if(!active.panning){let won=false;if(!active.moved&&rotationEnabled){active.group.rotation=((active.group.rotation||0)+1)%4;if(bevelEnabled)delete active.group.bitmapCache;won=tryLocks(active.group)}else if(active.moved)won=tryLocks(active.group);if(active.moved||rotationEnabled){moves++;sessionDirty=true;document.querySelector('#moves').textContent=String(moves).padStart(2,'0')}active=null;staticFrame=null;if(navigationFrame){navigationFrame=null;navigationBase=null;navigationExcluded=null;scheduleCacheRefinement()}updateProgress();draw();if(won)showWin()}else{active=null;settleNavigation()}try{canvas.releasePointerCapture(event.pointerId)}catch{}});
canvas.addEventListener('pointercancel',()=>{cancelNavigationDraw();stopEdgePan();active=null;staticFrame=null;navigationFrame=null;navigationBase=null;navigationExcluded=null;draw()});
canvas.addEventListener('pointerleave',()=>{if(!active&&hovered){hovered=null;draw()}});
function updateProgress(){const largest=Math.max(...groups.map(g=>g.ids.length)),percent=Math.round(largest/pieces.length*100);document.querySelector('#percent').textContent=`${percent}%`;document.querySelector('#progress').style.width=`${percent}%`}
function showWin(){clearInterval(timer);gameWon=true;completionShadowsDisabled=layout.mobile;winStartedAt=performance.now();sessionDirty=true;draw(winStartedAt)}
function formatTime(value){return `${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`}
function restart(){clearInterval(timer);if(winAnimationFrame)cancelAnimationFrame(winAnimationFrame);winAnimationFrame=null;winStartedAt=0;rippleStartedAt=0;rippleOrigin=null;completionShadowsDisabled=false;moves=0;seconds=0;gameStarted=true;gameWon=false;sessionDirty=false;view={zoom:1,panX:0,panY:0};document.querySelector('#boardZoom').value=100;document.querySelector('#zoomValue').value='100%';document.querySelector('#moves').textContent='00';document.querySelector('#time').textContent='00:00';makePieces();scatter();invalidateRenderCaches();updateProgress();draw();timer=setInterval(()=>{seconds++;document.querySelector('#time').textContent=formatTime(seconds)},1000)}
function resetCropControls(){crop={sx:0,sy:0,sw:image.naturalWidth,sh:image.naturalHeight,targetW:image.naturalWidth,targetH:image.naturalHeight};document.querySelector('#cropEditor').hidden=false;requestAnimationFrame(updateCropPreview);renderLevels()}
function cropValues(){return crop||{sx:0,sy:0,sw:image.naturalWidth,sh:image.naturalHeight,targetW:image.naturalWidth,targetH:image.naturalHeight}}
function updateCropPreview(){if(!image.naturalWidth)return;const preview=document.querySelector('#cropCanvas'),box=preview.parentElement.clientWidth;if(!box){cropMetrics=null;return}const w=box,h=Math.min(560,Math.max(300,w*.7)),ratio=Math.min(devicePixelRatio||1,3);preview.width=w*ratio;preview.height=h*ratio;preview.style.width=`${w}px`;preview.style.height=`${h}px`;const c=preview.getContext('2d');c.setTransform(ratio,0,0,ratio,0,0);c.clearRect(0,0,w,h);const scale=Math.min(w/image.naturalWidth,h/image.naturalHeight),dw=image.naturalWidth*scale,dh=image.naturalHeight*scale,ox=(w-dw)/2,oy=(h-dh)/2,value=cropValues(),rx=ox+value.sx*scale,ry=oy+value.sy*scale,rw=value.sw*scale,rh=value.sh*scale;c.drawImage(image,ox,oy,dw,dh);c.fillStyle='rgba(16,20,18,.58)';c.fillRect(ox,oy,dw,dh);c.save();c.beginPath();c.rect(rx,ry,rw,rh);c.clip();c.drawImage(image,ox,oy,dw,dh);c.restore();c.strokeStyle='#ee5b32';c.lineWidth=3;c.strokeRect(rx,ry,rw,rh);c.strokeStyle='rgba(255,255,255,.65)';c.lineWidth=1;for(const fraction of[1/3,2/3]){c.beginPath();c.moveTo(rx+rw*fraction,ry);c.lineTo(rx+rw*fraction,ry+rh);c.moveTo(rx,ry+rh*fraction);c.lineTo(rx+rw,ry+rh*fraction);c.stroke()}const handle=11;c.fillStyle='#fff';c.strokeStyle='#ee5b32';c.lineWidth=3;for(const[x,y]of[[rx,ry],[rx+rw,ry],[rx,ry+rh],[rx+rw,ry+rh]]){c.fillRect(x-handle/2,y-handle/2,handle,handle);c.strokeRect(x-handle/2,y-handle/2,handle,handle)}cropMetrics={scale,ox,oy,rx,ry,rw,rh,w,h}}
function loadImage(url,blob=null){imageBlob=blob;const next=new Image();next.referrerPolicy='no-referrer';next.onload=()=>{image=next;resetCropControls();if(!pieces.length){makePieces();scatter();draw()}};next.onerror=()=>alert('That image host blocked the request or the address is not a direct image link. Try downloading it and choosing it from your device.');next.src=url}
function useClipboardImage(blob){if(!blob?.type?.startsWith('image/'))return false;if(localUrl)URL.revokeObjectURL(localUrl);localUrl=URL.createObjectURL(blob);imageUrl=localUrl;address.value='';loadImage(imageUrl,blob);return true}
async function readClipboardImage(){try{if(!navigator.clipboard?.read)throw new Error('unsupported');const items=await navigator.clipboard.read();for(const item of items){const type=item.types.find(value=>value.startsWith('image/'));if(type&&useClipboardImage(await item.getType(type)))return}alert('The clipboard does not contain an image. Copy an image, then try again.')}catch(error){if(error?.name==='NotAllowedError')alert('Clipboard access was blocked. Allow clipboard permission for this site, or press Ctrl+V / Command+V while the puzzle window is open.');else alert('This browser cannot read images with that button. Press Ctrl+V / Command+V while the puzzle window is open instead.')}}
function renderLevels(){const root=document.querySelector('#levels');root.innerHTML='';Object.keys(LEVELS).forEach(name=>{const previous=level;level=name;const[cols,rows]=gridForLevel();level=previous;const button=document.createElement('button');button.className=name===level?'active':'';button.innerHTML=`<strong>${name}</strong><small>${cols} × ${rows} · ${cols*rows}</small>`;button.onclick=()=>{level=name;renderLevels()};root.append(button)})}
async function openSetup(){if(gameStarted&&!gameWon&&sessionDirty){if(confirm('Save your current session before starting a new puzzle?')){if(!await saveSession(true))return}else if(!confirm('Start a new puzzle without saving this session?'))return}clearInterval(timer);pendingSessionId=createSessionId();puzzleName=await uniquePuzzleName(defaultPuzzleName(pendingSessionId));document.querySelector('#puzzleName').value=puzzleName;const saves=await refreshSessionList();document.querySelector('#createPuzzlePanel').hidden=!!saves.length;document.querySelector('#setupOverlay').hidden=false;document.body.classList.add('setupOpen')}
document.querySelector('#showNewPuzzle').onclick=()=>{document.querySelector('#allowRotation').checked=true;showPuzzleCreator()};
const importSessionFile=document.querySelector('#importSessionFile');document.querySelectorAll('.importSession').forEach(button=>button.onclick=()=>importSessionFile.click());importSessionFile.onchange=async event=>{const[file]=event.target.files;event.target.value='';await importSession(file)};
document.querySelector('#backToSessions').onclick=()=>{document.querySelector('#createPuzzlePanel').hidden=true;document.querySelector('#savedSessions').hidden=false;document.querySelector('#savedSessions').scrollIntoView({block:'start'})};
document.querySelector('#restartTop').onclick=openSetup;document.querySelector('#startPuzzle').onclick=async()=>{crop=cropValues();rotationEnabled=document.querySelector('#allowRotation').checked;currentSessionId=pendingSessionId||createSessionId();puzzleName=await uniquePuzzleName(document.querySelector('#puzzleName').value||defaultPuzzleName(currentSessionId),currentSessionId);document.querySelector('#puzzleName').value=puzzleName;pendingSessionId=null;document.querySelector('#setupOverlay').hidden=true;document.body.classList.remove('setupOpen');restart();await saveSession(true)};document.querySelector('#useImage').onclick=()=>{if(address.value.trim()){imageUrl=address.value.trim();loadImage(imageUrl)}};address.onkeydown=e=>{if(e.key==='Enter')document.querySelector('#useImage').click()};document.querySelector('#upload').onclick=()=>document.querySelector('#fileInput').click();document.querySelector('#pasteImage').onclick=readClipboardImage;document.querySelector('#fileInput').onchange=e=>{const file=e.target.files[0];if(file)useClipboardImage(file)};document.addEventListener('paste',event=>{if(document.querySelector('#setupOverlay').hidden)return;const item=[...event.clipboardData.items].find(value=>value.type.startsWith('image/'));if(item){event.preventDefault();useClipboardImage(item.getAsFile())}});
document.querySelector('#resetSite').onclick=event=>{event.preventDefault();location.reload()};
let previewPinned=false,previewToken=0,previewHideTimer=null,keyboardPreviewHeld=false;
function showImagePopup(previewImage,source){const popup=document.querySelector('#previewPopup'),previewCanvas=document.querySelector('#previewPopupCanvas'),maxW=window.innerWidth,maxH=window.innerHeight,ratio=source.sw/source.sh;let w=maxW,h=w/ratio;if(h>maxH){h=maxH;w=h*ratio}const ratioDpr=Math.min(devicePixelRatio||1,3);previewCanvas.width=w*ratioDpr;previewCanvas.height=h*ratioDpr;previewCanvas.style.width=`${w}px`;previewCanvas.style.height=`${h}px`;const previewContext=previewCanvas.getContext('2d');previewContext.setTransform(ratioDpr,0,0,ratioDpr,0,0);previewContext.imageSmoothingEnabled=true;previewContext.imageSmoothingQuality='high';previewContext.drawImage(previewImage,source.sx,source.sy,source.sw,source.sh,0,0,w,h);clearTimeout(previewHideTimer);popup.hidden=false;requestAnimationFrame(()=>popup.classList.add('isVisible'))}
function showPreviewPopup(){previewToken++;showImagePopup(image,crop||{sx:0,sy:0,sw:image.naturalWidth,sh:image.naturalHeight})}
function hideMainPreview(){const popup=document.querySelector('#previewPopup');popup.classList.remove('isVisible');clearTimeout(previewHideTimer);previewHideTimer=setTimeout(()=>{if(!popup.classList.contains('isVisible'))popup.hidden=true},100)}
function hidePreviewPopup(){previewToken++;if(!previewPinned){hideMainPreview();document.querySelector('#savedPreviewPopup').hidden=true}}
function showSavedImagePopup(savedImage,source,button){const popup=document.querySelector('#savedPreviewPopup'),savedCanvas=document.querySelector('#savedPreviewCanvas'),ratio=source.sw/source.sh,maxW=Math.min(260,window.innerWidth*.65),maxH=200;let w=maxW,h=w/ratio;if(h>maxH){h=maxH;w=h*ratio}const ratioDpr=Math.min(devicePixelRatio||1,2);savedCanvas.width=w*ratioDpr;savedCanvas.height=h*ratioDpr;savedCanvas.style.width=`${w}px`;savedCanvas.style.height=`${h}px`;const savedContext=savedCanvas.getContext('2d');savedContext.setTransform(ratioDpr,0,0,ratioDpr,0,0);savedContext.drawImage(savedImage,source.sx,source.sy,source.sw,source.sh,0,0,w,h);popup.hidden=false;const rect=button.getBoundingClientRect(),row=button.closest('.sessionRow')?.getBoundingClientRect()||rect,popupW=w+16,popupH=h+16,leftSide=rect.left-popupW-10;let left,top;if(leftSide>=10){left=leftSide;top=Math.min(window.innerHeight-popupH-10,rect.top)}else{left=Math.min(window.innerWidth-popupW-10,Math.max(10,row.left));top=row.bottom+10;if(top+popupH>window.innerHeight-10)top=Math.max(10,row.top-popupH-10)}popup.style.left=`${Math.max(10,left)}px`;popup.style.top=`${Math.max(10,top)}px`}
async function showSavedPreview(saved,button){const token=++previewToken;try{let url=saved.imageUrl,tempUrl=null;if(saved.imageBlob){tempUrl=URL.createObjectURL(saved.imageBlob);url=tempUrl}if(!url)return;const savedImage=await loadImagePromise(url);if(tempUrl)URL.revokeObjectURL(tempUrl);if(token!==previewToken)return;const source=saved.crop||{sx:0,sy:0,sw:savedImage.naturalWidth,sh:savedImage.naturalHeight};showSavedImagePopup(savedImage,source,button)}catch{if(token===previewToken)document.querySelector('#savedPreviewPopup').hidden=true}}
function bindSavedPreview(button,saved){button.addEventListener('pointerenter',event=>{if(event.pointerType==='mouse'&&!previewPinned)showSavedPreview(saved,button)});button.addEventListener('pointerleave',hidePreviewPopup);button.addEventListener('click',event=>{event.stopPropagation();previewPinned=!previewPinned;if(previewPinned)showSavedPreview(saved,button);else{previewToken++;document.querySelector('#savedPreviewPopup').hidden=true}})}
const preview=document.querySelector('#preview'),previewPopup=document.querySelector('#previewPopup');preview.addEventListener('pointerenter',event=>{if(event.pointerType==='mouse'&&!previewPinned)showPreviewPopup()});preview.addEventListener('pointerleave',hidePreviewPopup);preview.addEventListener('focus',()=>{if(!previewPinned)showPreviewPopup()});preview.addEventListener('blur',hidePreviewPopup);preview.addEventListener('click',event=>{event.stopPropagation();previewPinned=!previewPinned;if(previewPinned)showPreviewPopup();else{previewToken++;hideMainPreview()}});document.addEventListener('click',event=>{if(previewPinned&&!event.target.closest('#preview,.previewSaved')){previewPinned=false;previewToken++;hideMainPreview();document.querySelector('#savedPreviewPopup').hidden=true}});
function acceptsTextInput(target){return target?.matches?.('textarea,[contenteditable="true"],input:not([type]),input[type="text"],input[type="url"],input[type="search"],input[type="email"],input[type="password"],input[type="number"]')}
function releaseKeyboardPreview(){if(!keyboardPreviewHeld)return;keyboardPreviewHeld=false;if(!previewPinned){previewToken++;hideMainPreview()}}
document.addEventListener('keydown',event=>{if(event.code!=='Space'||event.repeat||!gameStarted||!document.querySelector('#setupOverlay').hidden||acceptsTextInput(event.target))return;event.preventDefault();keyboardPreviewHeld=true;showPreviewPopup()},true);
document.addEventListener('keyup',event=>{if(event.code==='Space'&&keyboardPreviewHeld){event.preventDefault();releaseKeyboardPreview()}},true);window.addEventListener('blur',releaseKeyboardPreview);
document.querySelector('#resetCrop').onclick=resetCropControls;
const cropCanvas=document.querySelector('#cropCanvas');
new ResizeObserver(entries=>{if(entries[0]?.contentRect.width&&document.querySelector('#createPuzzlePanel').hidden===false)updateCropPreview()}).observe(cropCanvas.parentElement);
function cropCanvasPoint(event){const rect=cropCanvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*cropMetrics.w/rect.width,y:(event.clientY-rect.top)*cropMetrics.h/rect.height}}
cropCanvas.addEventListener('pointerdown',event=>{if(!cropMetrics)return;event.preventDefault();const point=cropCanvasPoint(event),{rx,ry,rw,rh}=cropMetrics,threshold=24,corners=[['nw',rx,ry],['ne',rx+rw,ry],['sw',rx,ry+rh],['se',rx+rw,ry+rh]],corner=corners.find(([,x,y])=>Math.hypot(point.x-x,point.y-y)<=threshold);if(corner)cropInteraction={mode:corner[0],start:point,initial:{...crop}};else if(point.x>=rx&&point.x<=rx+rw&&point.y>=ry&&point.y<=ry+rh)cropInteraction={mode:'move',start:point,initial:{...crop}};if(cropInteraction)cropCanvas.setPointerCapture(event.pointerId)});
cropCanvas.addEventListener('pointermove',event=>{if(!cropMetrics)return;const point=cropCanvasPoint(event);if(!cropInteraction){const{rx,ry,rw,rh}=cropMetrics,nearCorner=[[rx,ry],[rx+rw,ry],[rx,ry+rh],[rx+rw,ry+rh]].some(([x,y])=>Math.hypot(point.x-x,point.y-y)<24);cropCanvas.style.cursor=nearCorner?'nwse-resize':point.x>=rx&&point.x<=rx+rw&&point.y>=ry&&point.y<=ry+rh?'move':'default';return}event.preventDefault();const dx=(point.x-cropInteraction.start.x)/cropMetrics.scale,dy=(point.y-cropInteraction.start.y)/cropMetrics.scale,start=cropInteraction.initial,minW=image.naturalWidth*.08,minH=image.naturalHeight*.08;let left=start.sx,top=start.sy,right=start.sx+start.sw,bottom=start.sy+start.sh;if(cropInteraction.mode==='move'){left=Math.max(0,Math.min(image.naturalWidth-start.sw,start.sx+dx));top=Math.max(0,Math.min(image.naturalHeight-start.sh,start.sy+dy));right=left+start.sw;bottom=top+start.sh}else{if(cropInteraction.mode.includes('w'))left=Math.max(0,Math.min(right-minW,start.sx+dx));if(cropInteraction.mode.includes('e'))right=Math.min(image.naturalWidth,Math.max(left+minW,start.sx+start.sw+dx));if(cropInteraction.mode.includes('n'))top=Math.max(0,Math.min(bottom-minH,start.sy+dy));if(cropInteraction.mode.includes('s'))bottom=Math.min(image.naturalHeight,Math.max(top+minH,start.sy+start.sh+dy))}crop={sx:left,sy:top,sw:right-left,sh:bottom-top,targetW:Math.round(right-left),targetH:Math.round(bottom-top)};updateCropPreview()});
function endCropInteraction(event){if(!cropInteraction)return;cropInteraction=null;renderLevels();try{cropCanvas.releasePointerCapture(event.pointerId)}catch{}}
cropCanvas.addEventListener('pointerup',endCropInteraction);cropCanvas.addEventListener('pointercancel',endCropInteraction);
function zoomLimit(){return 10}
function setZoom(value,anchor=null){const next=Math.max(.25,Math.min(zoomLimit(),value));beginNavigation();if(anchor){const cx=layout.width/2,cy=layout.height/2,worldX=(anchor.x-cx-view.panX)/view.zoom+cx,worldY=(anchor.y-cy-view.panY)/view.zoom+cy;view.panX=anchor.x-cx-next*(worldX-cx);view.panY=anchor.y-cy-next*(worldY-cy)}view.zoom=next;staticFrame=null;document.querySelector('#boardZoom').value=Math.round(view.zoom*100);document.querySelector('#zoomValue').value=`${Math.round(view.zoom*100)}%`;requestNavigationDraw();settleNavigation()}
document.querySelector('#boardZoom').oninput=e=>setZoom(Number(e.target.value)/100);document.querySelector('#zoomOut').onclick=()=>setZoom(view.zoom-.1);document.querySelector('#zoomIn').onclick=()=>setZoom(view.zoom+.1);document.querySelector('#centerView').onclick=()=>{view.panX=0;view.panY=0;draw()};
document.querySelector('#reshuffleLoose').onclick=reshuffleLoose;
document.querySelector('#saveSession').onclick=()=>saveSession(false);
canvas.addEventListener('wheel',event=>{event.preventDefault();const anchor=screenPointer(event),factor=Math.exp(-event.deltaY*.0015);setZoom(view.zoom*factor,anchor)},{passive:false});
function touchPoint(touch){const rect=canvas.getBoundingClientRect();return{x:(touch.clientX-rect.left)*layout.width/rect.width,y:(touch.clientY-rect.top)*layout.height/rect.height}}
canvas.addEventListener('touchstart',event=>{if(event.touches.length!==2)return;event.preventDefault();active=null;beginNavigation();const a=touchPoint(event.touches[0]),b=touchPoint(event.touches[1]),mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};pinchGesture={distance:Math.hypot(b.x-a.x,b.y-a.y),zoom:view.zoom,mid,panX:view.panX,panY:view.panY}},{passive:false});
canvas.addEventListener('touchmove',event=>{if(!pinchGesture||event.touches.length!==2)return;event.preventDefault();const a=touchPoint(event.touches[0]),b=touchPoint(event.touches[1]),mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2},distance=Math.hypot(b.x-a.x,b.y-a.y),next=Math.max(.25,Math.min(zoomLimit(),pinchGesture.zoom*distance/pinchGesture.distance));view.panX=pinchGesture.panX;view.panY=pinchGesture.panY;view.zoom=pinchGesture.zoom;setZoom(next,pinchGesture.mid);view.panX+=mid.x-pinchGesture.mid.x;view.panY+=mid.y-pinchGesture.mid.y;requestNavigationDraw()},{passive:false});
canvas.addEventListener('touchend',event=>{if(event.touches.length<2){pinchGesture=null;settleNavigation()}},{passive:true});canvas.addEventListener('touchcancel',()=>{pinchGesture=null;settleNavigation()},{passive:true});
window.addEventListener('resize',()=>{if(!pieces.length)return;const old=layout;fitLayout();groups.forEach(group=>{group.dx*=layout.boardW/old.boardW;group.dy*=layout.boardH/old.boardH});view.panX*=layout.width/old.width;view.panY*=layout.height/old.height;invalidateRenderCaches();draw()});window.addEventListener('beforeunload',event=>{if(gameStarted&&!gameWon&&sessionDirty){event.preventDefault();event.returnValue=''}if(localUrl)URL.revokeObjectURL(localUrl)});
pendingSessionId=createSessionId();puzzleName=defaultPuzzleName(pendingSessionId);document.querySelector('#puzzleName').value=puzzleName;renderLevels();document.body.classList.add('setupOpen');loadImage(DEFAULT_IMAGE);refreshSessionList().then(saves=>document.querySelector('#createPuzzlePanel').hidden=!!saves.length);
